### ISSUE TITLE
Changing resolution within a scenario causes a crash

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#133]
A wishlist item. Changing the resolution within a scenario causes a crash after moving the mouse to the bottom-right; it would be nice to solve this, so that an option for changing resolution during a scenario could be added to Stratagus games.

---

Imported from Launchpad using lp2gh.
- date created: 2015-03-21T09:15:38Z
- owner: andre-ng
- the launchpad url was https://bugs.launchpad.net/bugs/1434784

**Comment by abenedic** [comment]
Can this be replicated on master currently? I can only run under wine currently due to various issues, but I didn't encounter this after changing resolution.

**Comment by timfel** [comment]
It doesn't crash, but it also doesn't do anything. There just is no option to change the video resolution after launching a game, which is kind of by design. I'll actually close this.
