### ISSUE TITLE
Wrong Tile Index being set in CMap::RegenerateForestTile

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#136]
The wrong Tile Index is being set in CMap::RegenerateForestTile. The two instances of setTileIndex in that function are as such:

topMf.setTileIndex(_Map.Tileset, Map.Tileset->getTopOneTreeTile(), 0);
[...]
mf.setTileIndex(_Map.Tileset, Map.Tileset->getBottomOneTreeTile(), 0);

But getTopOneTreeTile() and getBottomOneTreeTile() do not return tile indexes at all, but the graphic tile (i.e., which frame of the tileset to get the tile's graphic from, rather than the actual tile index of that sort of tile). To solve this, doing the following is needed: first, replace those instances of setTileIndex with these ones:

topMf.setTileIndex(_Map.Tileset, Map.Tileset->getDefaultWoodTileIndex(), 0);
[...]
mf.setTileIndex(_Map.Tileset, Map.Tileset->getDefaultWoodTileIndex(), 0);

...and then, add the following function to tileset.cpp (I added it just below CTileset::getDefaultTileIndex()):

unsigned int CTileset::getDefaultWoodTileIndex() const
{
    const int n = tiles.size();
    int solid = 0;
    for (int i = 0; i < n;) {
        const CTile &tile = tiles[i];
        const CTileInfo &tileinfo = tile.tileinfo;
        if (tileinfo.BaseTerrain && tileinfo.MixTerrain) {
            i += 256;
        } else {
            if (tileinfo.BaseTerrain != 0 && tileinfo.MixTerrain == 0) {
                if (tile.flag & MapFieldForest) {
                    solid = i;
                }
            }
            i += 16;
        }
    }
    return solid;
}

...and of course, that function in tileset.h:

unsigned int getDefaultWoodTileIndex() const;

...and that's all :)

---

Imported from Launchpad using lp2gh.
- date created: 2015-03-29T09:04:39Z
- owner: andre-ng
- the launchpad url was https://bugs.launchpad.net/bugs/1437798

**Comment by timfel** [comment]
@Andrettin can you cherry-pick the patch for doing this from Wyrmgus into Stratagus?

**Comment by Andrettin** [comment]
@timfel You mean linking the specific commit that did it?
