### ISSUE TITLE
Unit sight is not symmetric

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#139]
Unit sight is not symmetric vertically. To solve this, replace this line in map_fog.cpp:

const int offsetx = isqrt(square(range + 1) - square(offsety) - 1);

...with this line:

const int offsetx = isqrt(square(range + 1) - square(offsety + 1) - 1);

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-04-18T19:44:59Z
 * owner: andre-ng
 * the launchpad url was https://bugs.launchpad.net/bugs/1445820

**Comment by Andrettin** [comment]
Fixed:
https://github.com/Wargus/stratagus/commit/40117f5cf43f574ef41727be69977df864734a35
