### ISSUE TITLE
Bug with CBuildRestrictionOnTop::Check function

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#140]
There is a bug with the CBuildRestrictionOnTop::Check function (\unit\build.cpp). This line:

Vec2i endPos(found.tilePos.x + found.Type->TileWidth, found.tilePos.y + found.Type->TileHeight);

...is wrong. It results in extra tiles being required to be emptied to the south and east of the resource. Replacing that line with this one fixes the issue:

Vec2i endPos(found.tilePos.x + found.Type->TileWidth - 1, found.tilePos.y + found.Type->TileHeight - 1);

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-04-21T11:51:08Z
 * owner: andre-ng
 * the launchpad url was https://bugs.launchpad.net/bugs/1446597

**Comment by Andrettin** [comment]
Fixed:
https://github.com/Wargus/stratagus/commit/40117f5cf43f574ef41727be69977df864734a35
