### ISSUE TITLE
Pathfinder Fix

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#141]
Currently, we have the following code in astar.cpp (CostMoveToCallBack_Default function):

					// for non moving unit Always Fail unless goal is unit, or unit can attack the target
					if (&unit != goal) {
						if (goal->Player->IsEnemy(unit) && unit.IsAgressive() && CanTarget(*unit.Type, *goal->Type)
							&& goal->Variable[UNHOLYARMOR_INDEX].Value == 0 && goal->IsVisibleAsGoal(*unit.Player)) {
								cost += 2 * AStarMovingUnitCrossingCost;
						} else {
						// FIXME: Need support for moving a fixed unit to add cost
							return -1;
						}
						//cost += AStarFixedUnitCrossingCost;
					}

The problem is that this makes melee units (or ranged units if the goal is outside range) keep trying to get to a target even if there is something blocking the way.

Modifying that code to this instead solves the issue:

					// for non moving unit Always Fail unless goal is unit, or unit can attack the target
					if (&unit != goal) {
						if (goal->Player->IsEnemy(unit) && unit.IsAgressive() && CanTarget(*unit.Type, *goal->Type)
							&& unit.MapDistanceTo(*goal) <= unit.Variable[ATTACKRANGE_INDEX].Max
							&& goal->Variable[UNHOLYARMOR_INDEX].Value == 0 && goal->IsVisibleAsGoal(*unit.Player)) {
								cost += 2 * AStarMovingUnitCrossingCost;
						} else {
						// FIXME: Need support for moving a fixed unit to add cost
							return -1;
						}
						//cost += AStarFixedUnitCrossingCost;
					}

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-04-23T15:33:10Z
 * owner: andre-ng
 * the launchpad url was https://bugs.launchpad.net/bugs/1447671

**Comment by Andrettin** [comment]
Closing because there were issues with this fix, so it wouldn't make sense to incorporate it into Stratagus
