### ISSUE TITLE
Cannot start single player games, or Campaign games

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#142]
I have an issue, under Wargus I cannot start a Single player game, nor can I start a Campaign game. I can start and play a Multiplayer game solo however. I extracted it using Wargus 2.3. If I click on Single player Standard game, or campaign game, I get the error: Error in Error handling on the console, and I am presented with a blank screen with no missions.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-05-07T09:19:48Z
 * owner: zombie-ryushu
 * the launchpad url was https://bugs.launchpad.net/bugs/1452634

**Comment by Andrettin** [comment]
"Error in Error handling" is almost always a Lua error. Shouldn't this be in the Wargus repo, though?

**Comment by timfel** [comment]
Closing this because it's linked to an old version of Wargus
