### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#145]
Stratagus has memory leaks regarding CUnitType, among other things. I think this is the culprit:

#ifdef DEBUG
 CleanModules();
 FreeBurningBuildingFrames();
 FreeSounds();
 FreeGraphics();
 FreePlayerColors();
 FreeButtonStyles();
 FreeAllContainers();
 freeGuichan();
 DebugPrint("Frames %lu, Slow frames %d = %ld%%\n" _C_
      FrameCounter _C_ SlowFrameCounter _C_
      (SlowFrameCounter * 100) / (FrameCounter ? FrameCounter : 1));
 lua_settop(Lua, 0);
 lua_close(Lua);
 DeInitVideo();
#endif

Why is this #ifdef DEBUG? That it is so means that unit types and etc. never get deleted in non-debug executables.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-06-02T20:02:22Z
 * owner: andre-ng
 * the launchpad url was https://bugs.launchpad.net/bugs/1461248

**Comment by Andrettin** [comment]
I don't really see any reason for this being under #ifdef DEBUG and it is causing memory leaks, so if no one has anything against it, I'm going to go ahead and remove the #ifdef DEBUG from this.

**Comment by timfel** [comment]
@Andrettin did you fix this one, can it be closed?

**Comment by Andrettin** [comment]
I've done it so far only in Wyrmgus, I was waiting to see if anyone had any objections to implementing it into Stratagus.

**Comment by timfel** [comment]
I think it's a good idea to remove the ifdef debug here.

**Comment by Andrettin** [comment]
Done:
https://github.com/Wargus/stratagus/commit/9a9940e5b37034879f7be3cbf721e687f7dc7e0b
