### ISSUE TITLE
Hotkeys Don't Work for Keyboard Layouts other than QWERTY

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#146]
Hotkeys don't work for keyboard layouts other than qwerty, such as colemak.
---

Imported from Launchpad using lp2gh.
- date created: 2015-06-08T19:07:45Z
- owner: andre-ng
- the launchpad url was https://bugs.launchpad.net/bugs/1463142

**Comment by a-detiste** [comment]
or azerty (Ctrl-1 ...)

**Comment by timfel** [comment]
This is due to SDL 1.2 not supporting localized keymaps. Switching to SDL2 will fix this, but not before.
