### ISSUE TITLE
Color Cycling Doesn't Work under OpenGL

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#147]
Color cycling doesn't work under OpenGL.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-06-09T19:22:41Z
 * owner: andre-ng
 * the launchpad url was https://bugs.launchpad.net/bugs/1463532

**Comment by DinkyDyeAussie** [comment]
Would be nice if it did. Color cycling gives the game so much atmosphere.

**Comment by timfel** [comment]
I opened a PR to fix this.
