### ISSUE TITLE
Menu screenshots appear completely black if shaders are active

### ISSUE THREAD

**Issue by Andrettin** [Wargus/stratagus#156]
If the shaders are active, screenshots made of the menu appear completely black. If playing with the "-x -1" command line, this doesn't happen.

**Comment by timfel** [comment]
Is that taking screenshots using the normal OS tools? What system are you on?

**Comment by Andrettin** [comment]
I'm on Windows 8. I meant the screenshots which Stratagus itself generates when pressing the "Print Screen" button.

Maybe it's due to this piece of code (in lines 287-293 of /video/sdl.cpp)?

``
#ifdef USE_OPENGL
	if (!GLShaderPipelineSupported) {
		glOrtho(0, Video.Width, Video.Height, 0, -1, 1);
	} else {
		glOrtho(0, Video.ViewportWidth, Video.ViewportHeight, 0, -1, 1);
	}
#endif
``

**Comment by timfel** [comment]
Oh, I didn't know about that feature. I'll look into it :)
