### ISSUE TITLE
Stop Stratagus from writing to the Installation folder on Windows

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#159]
This interferes with UAC and requires running as admin. It should write logs and screenshots to the user directory.

**Comment by Kintobor** [comment]
Set ENABLE_USEGAMEDIR to false.

**Comment by timfel** [comment]
The variable is set to false, and the user data is indeed saved to the user directory. I'm talking about stderr.txt and stdout.txt that are generated in the exe directory

**Comment by timfel** [comment]
Ok, it seems this is SDL doing the redirect. This can be fixed by building and shipping our own SDL, but maybe it's not that important.

**Comment by pali** [comment]
Hi! Please check older versions hosted on Launchpad. This problem with stderr.txt and stdout.txt was there fixed!

**Comment by timfel** [comment]
Do you remember which older version? Do you mean you shipped a different SDL with those?

I thought a fix could be to just redirect the output back to the console (after `SDL_Init`), but that seems not good enough for windows' uae, because it already complains when `SDL_Init` calls `freopen("stdout.txt", "w", stdout)` (even though we're never writing to it).

**Comment by timfel** [comment]
Should be fixed.

**Comment by pali** [comment]
Do not remember, but I think that there was SDL library compiled without that redirection.

**Comment by timfel** [comment]
Yeah, dont worry about it, I made a repo to compile our own SDL lib (and all other win32 deps). SDL is compiled with  the  option to not do that redirection
