### ISSUE TITLE
Rectangles incorrectly drawn under OpenGL

### ISSUE THREAD

**Issue by Andrettin** [Wargus/stratagus#167]
In OpenGL rectangles are drawn incorrectly (i.e. missing a couple of pixels are the end of a line). Under SDL this problem does not occur.

**Comment by timfel** [comment]
Can you post a screenshot that shows the problem?

**Comment by Andrettin** [comment]
It is very noticeable - any rectangle drawn under OpenGL is a pixel off.

Here is an example:
https://dl.dropboxusercontent.com/u/1732902/Stratagus/rectangles_issue.png


The green rectangle around player 0's square has one extra pixel in the top-right, and one extra pixel in the bottom-right. The same happens for the rectangles around the selection and unit icons. The cross in the start location button also has one extra pixel in nearly all directions.

**Comment by timfel** [comment]
Should be better now:

Before:
![before](https://cloud.githubusercontent.com/assets/46235/12811996/46a8f3bc-cb30-11e5-8cc3-928517bed45b.png)

After: 
![after](https://cloud.githubusercontent.com/assets/46235/12811997/46aa0400-cb30-11e5-9360-4ca36ac5d4c1.png)

**Comment by timfel** [comment]
Feel free to re-open if this wasn't actually the (entire) problem.

**Comment by DinkyDyeAussie** [comment]
That easy huh... :)

**Comment by Andrettin** [comment]
Tim, the selection rectangle is indeed better now, but there is some weirdness now for the rectangles in the editor (the player-colored rectangles for instance are now not entirely filled).

I've fixed the rectangle issue with this code instead, and it seems to me that it works better:

```
#ifdef USE_OPENGL
	glBegin(GL_LINES);
	glVertex2i(x, y);
	//Wyrmgus start
//	glVertex2i(x + w, y);
	glVertex2i(x + w - 1, y);
	//Wyrmgus end

	glVertex2i(x + w - 1, y + 1);
	//Wyrmgus start
//	glVertex2i(x + w - 1, y + h);
	glVertex2i(x + w - 1, y + h - 1);
	//Wyrmgus end

	glVertex2i(x + w - 1, y + h - 1);
	glVertex2i(x, y + h - 1);

	glVertex2i(x, y + h - 1);
	glVertex2i(x, y + 1);
	glEnd();
#endif
```

```
	if (top) {
		//Wyrmgus start
//		DrawHLine(color, x, y, w);
		DrawHLine(color, x, y, w - 1);
		//Wyrmgus end
		if (!--h) {
			return;                    // rectangle as horizontal line
		}
		++y;
	}
	if (bottom) {
		//Wyrmgus start
//		DrawHLine(color, x, y + h - 1, w);
		DrawHLine(color, x, y + h - 1, w - 1);
		//Wyrmgus end
		--h;
	}
	if (left) {
		DrawVLine(color, x, y, h);
		if (!--w) {
			return;                    // rectangle as vertical line
		}
		++x;
	}
	if (right) {
		DrawVLine(color, x + w - 1, y, h);
	}

```

...though, there is still some issue with the alignment of the selection boxes with this code.
