### ISSUE TITLE
Rescue players can capture themselves

### ISSUE THREAD

**Issue by Kintobor** [Wargus/stratagus#169]
Rescue players can capture themselves.

**Comment by Andrettin** [comment]
If the rescue player is (somehow) controlled by a person? Or by a computer?

**Comment by Kintobor** [comment]
The rescue player is controlled by an active ai. When the peasants move around they keep capturing their own buildings.

**Comment by Andrettin** [comment]
Should be fixed now:
https://github.com/Wargus/stratagus/commit/0b568e7d38ee48c8149e20df788b294a27f697c8
