### ISSUE TITLE
Audio Thread leads to lockups

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#171]
I am experiencing lockups *only* on Linux since merging @marcelofg55's patch #165. Attaching gdb shows that `PlaySample` is hanging trying to acquire the lock. This happens reproducibly only in multiplayer games as soon as I click the first unit. Solo games work fine.

**Comment by Andrettin** [comment]
There was the same issue with Wyrmsun/Wyrmgus, but marcelofg55 kindly submitted a patch to solve the issue. I believe this is the commit which solved it:
https://github.com/Andrettin/Wyrmgus/commit/7d891153a498026287e17db8288cb23b1da00784

**Comment by marcelofg55** [comment]
Just submitted a pull request that fixes this.

**Comment by Andrettin** [comment]
Fixed:
https://github.com/Wargus/stratagus/commit/aa4d9045bd6bfbea811ba92f94c3e0a18cd48e8e
