### ISSUE TITLE
Request Rebuild of Current Master on Windows

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#173]
I'dd like to request that the current Master Branch of Stratagus on Windows be rebuilt, with instructions and dependencies.

**Comment by timfel** [comment]
What do you mean "with instructions and dependencies"? Builds are available from the release page, they are always from the current master (if it did compile)

**Comment by Zombie-Ryushu** [comment]
SDL Windows DLLs basically.

**Comment by timfel** [comment]
That installer does have all required dlls, and it is from the most recent master. The November date is the date the title of that release was last updated, as I said, the installer exe is updated on every commit
