### ISSUE TITLE
Make lua51 optional, add support for lua5.2, lua5.3

### ISSUE THREAD

**Issue by KroArtem** [Wargus/stratagus#178]
Does stratagus depend on exact 5.1 version of lua? I've got 5.2 installed by default and do not want to install 5.1 Moreover, 5.2 is not an up-to-date version, 5.3.x was released in 2015.

**Comment by timfel** [comment]
I don't know, many things changed since 5.1, but really, I don't think anybody tried to compile with newer versions at least for some time. You could just try it. The main thing to not is that we're using tolua++, for which I also don't know how far behind Lua they are

**Comment by timfel** [comment]
Ok, looks like tolua++ is an issue. It won't support anything newer than 5.1

**Comment by KroArtem** [comment]
According to these pages:
[toluapp](https://github.com/LuaDist/toluapp), which was even forked to another Stratagus repo (which contains some interesting things, btw) and some less trusted link [toluapp](https://github.com/waltervn/toluapp) there is some support for tolua++. I haven't checked these things by myself but lua 5.2 and 5.3 are claimed to be working.

**Comment by timfel** [comment]
@KroArtem I hadn't seen https://github.com/waltervn/toluapp. Looks like it would be worth a try. If you want to give it a shot, we'd be happy to get pull requests :)

**Comment by KroArtem** [comment]
If I have time, I'll have a look at tolua++ on the first link. Its cmake file seem to respect lua 5.2/5.3. However, it's not my top priority. :)

**Comment by timfel** [comment]
After running a few benchmarks, it seems that 5.2/5.3 are significantly slower than lua 5.1. I mean, it probably doesn't matter much given the architecture of stratagus, but just saying.

**Comment by timfel** [comment]
And come to think of it, why not switch to LuaJIT?

**Comment by KroArtem** [comment]
I googled about 5.1/5.2/5.3 performance and you may be indeed right about slowness of next versions. Regarding LuaJIT: that sounds reasonable only in case no significant changes should be done in scripts. That's where we should ask @Andrettin :)

**Comment by timfel** [comment]
I tried luajit, the shared library / dll is binary compatible with lua 5.1, no changes required.

**Comment by timfel** [comment]
Since this would take a lot of effort that nobody is willing to expend (hey, we're still using SDL 1.2), I'm closing this
