### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by machinewars** [Wargus/stratagus#179]
Hi guys,

I saw this sort of in another thread. I emailed Kyran, but I seem to be having difficulties. I downloaded Stratagus 2.4. Installed it. I double clicked the .exe file, I got an error saying the VCRUNTIME140.DLL was missing.

I was advised to download the latest Visual Studio Run Time Files the x86 2015 one. I got that and installed it.

I don't get the .dll error anymore, however now the .exe doesn't load anything when I click it.

**Comment by machinewars** [comment]
"Maybe you need to specify another gamepath with '-d /path/to/datadir'?"

This forms in the text document after I try to load it.

**Comment by Kintobor** [comment]
You need a game to go with Stratagus. Stratagus doesn't do anything by itself.
