### ISSUE TITLE
Compilation of latest trunk build

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#180]
Using Visual Studio 2012 here to compile the source code. I have sorted out CMake and made sure to include all the dependencies I can. Now I have everything setup in Visual Studio to the best of my knowledge.

I get a couple of errors when I build. Would appreciate some help with this.

```
3>libpng.lib(pngget.obj) : error LNK2019: unresolved external symbol __dtoui3 referenced in function _png_get_pHYs_dpi
3>libpng.lib(pngerror.obj) : error LNK2019: unresolved external symbol __imp____acrt_iob_func referenced in function _png_default_error
3>libpng.lib(pngerror.obj) : error LNK2019: unresolved external symbol __imp____stdio_common_vfprintf referenced in function __vfprintf_l
3>D:\Games\Stratagus\build\Debug\png2stratagus.exe : fatal error LNK1120: 3 unresolved externals
4>  color.cpp
4>  color.cpp
4>LINK : fatal error C1007: unrecognized flag '-FitObjData' in 'p2'
4>LINK : fatal error LNK1257: code generation failed
6>------ Build started: Project: ALL_BUILD, Configuration: Debug Win32 ------
========== Build: 4 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

Any ideas? I'll be patient :palm_tree:

**Comment by timfel** [comment]
Is that using the dependencies.zip provided here on github? If that is the case, these have been compiled with VS2015, so might not on older versions. Sorry :/

**Comment by DinkyDyeAussie** [comment]
Yeah used the dependencies on github. No worries man I'll install the C++ component of vs2015 soon and it should all be good then! Thanks for that :-)
