### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by mimooh** [Wargus/stratagus#183]
I suggest new stratagus is released, since for me and other people there were really major improvements lately. I also contacted stratagus.com and perhaps github and where to download will be more emphasized on that site. I also think we can have a better logo than this: http://stratagus.com/wp-content/themes/Karma/images/_global/custom-logo-2.png. I do graphics (https://commons.wikimedia.org/w/index.php?search=mimooh) so, perhaps I come out with something. A knight perhaps.

**Comment by timfel** [comment]
Cool! Thank you!

I agree that a new release should happen fairly soon, but before I would like to go into beta phase to verify things work across multiple platforms. The installers have changed and need to be checked, for example. We support OS X as a new platform, and I have only tested the OS X Wargus bundle on one Macbook so far (I can test on a bunch of different Macs, if nobody else has time, but I'm fairly busy right now and won't have time to debug if any issues crop up). @Mistranger also pointed out various issues (translation problems in the installer, Battle.net Edition support) that need to be checked.

Btw, really nice graphics. If you could create a nice logo, that would be awesome. This one is getting old ;) ![image](https://cloud.githubusercontent.com/assets/46235/13219425/379a51c4-d970-11e5-92b5-1c9fe2f61450.png)

**Comment by DinkyDyeAussie** [comment]
If this doesn't belong here I am sorry. But color cycling does not work in OpenGL mode on windows. You guys said it did didn't you?

**Comment by timfel** [comment]
@DinkyDyeAussie Hm, it works here. What version of Windows are you on? Any output in the logs? What game do you use?

**Comment by DinkyDyeAussie** [comment]
I'm on Windows 10. Using the latest version builds of both Wargus and Stratagus. No output logs. Is there a certain command line parameter I need to use to get that?

**Comment by timfel** [comment]
Found the issue, I had changed with my scripts and forgot. I just pushed a fix.

**Comment by timfel** [comment]
You'll only need to update Stratagus (once its built)

**Comment by mimooh** [comment]
Not finished, but how about one of these: http://www.inf.sgsp.edu.pl/pub/MALUNKI/NOWE/stratagus.svg. Icon is another thing and I'm not good at those, but I will try to tweak it into low resolution.

**Comment by Kintobor** [comment]
Our new mascot? Sir Stratalot?

**Comment by Kintobor** [comment]
mimooh, you are welcome to create new contact for the website. If you post it here or in the forums I'll upload it.

While I'm here, why are we Wargus/stratagus and not Stratagus/stratagus?

**Comment by timfel** [comment]
Because I don't know who owns the Stratagus account and they didn't answer my email

**Comment by mimooh** [comment]
> Our new mascot? Sir Stratalot?
Stratalot... sounds good :) 

As it comes to stratagus.com. I am not sure to which release point to
right now. I'd say 2.4 is better than 2.3, but let's wait a while more
with this. Stratagus is pretty much minimalistic, which is good. But I
get the feeling that it could point to better URLs: more active talk is
on github than on forums. Also there's a mess with stratagus.com,
sf.net, launchpad.net, github and all of these are mentioned here and
there... From most of these sites it's hard to learn that multiplayer is
fixed finally (btw, I played windows vs linux yesterday and it was not
desyncing :). Also, are all games mentioned on stratagus.com really
working? 

Just learned about this:
https://pages.github.com/

Maybe this would be the right place and everything could be redirected
to pages.github.com? There are two advantages at least: a) integration
with github and b) collaborative site. I could start with the site if
you think such a new site on github makes sense.

-- 
Karol Kreński

**Comment by timfel** [comment]
I do think pointing stratagus.com to github pages would be the best way forward w.r.t. collaborative updating of the content. It's mostly static content, anyway, and the rest can be done with Javascript. Btw, who's paying for stratagus.com?

**Comment by mimooh** [comment]
Sir Stratalot is ready and I am happy how it came out: 
http://mimooh.github.io/wargus/

Hope you like this image. @timfel, if you start with this new stratagus github pages I hope I can be added as an collaborator. The svg source for the above images are available in my repo:
https://github.com/mimooh/wargus/tree/gh-pages/site

**Comment by Kintobor** [comment]
I think 2.3 was better than 2.4, but 2.5 will be the best.

The website had all that collaborative stuff, even has a wiki. No one ever used it so it got hidden. A blog as the Stratagus homepage was toyed with, but no one had anything to write for it.

Sir Stratalot looks pretty neato! Do that horsey one next. :D

**Comment by mimooh** [comment]
> I think 2.3 was better than 2.4, but 2.5 will be the best.
No other version will give me more joy than 2.4. Tim is gonna get Alan
Turing award for fixing this nasty out-of-sync for a decade almost. And
Andrettin too. They should share it with valgrind developers.
 
> The website had all that collaborative stuff, even has a wiki. No one
> ever used it so it got hidden. A blog as the Stratagus homepage was
> toyed with, but no one had anything to write for it.
I know how it is, you put your heart to that site, but github is modern
and fancy and everything should be moved there, you know :) Even though
I feel quite lost whenever I am about to make all these git pushes and
merges and branches... 
 
> Sir Stratalot looks pretty neato! 
Sure he does! I spent quite a few hours polishing the details that you
won't even ever see :)

> Do that horsey one next. :D
No horsey, at least for now. I can make an icon instead.

-- 
Karol Kreński

**Comment by Kintobor** [comment]
>github is modern and fancy and everything should be moved there, you know
Sourceforge, Launchpad, GitHub. How many places has Stratagus lived?

>No horsey, at least for now.
Why do you hurt me so?

**Comment by timfel** [comment]
@mimooh you have an invite :)

**Comment by mimooh** [comment]
> @mimooh you have an invite :)
Thx :) Seems like I have no excuse to finally learn this git thing. 

-- 
Karol Kreński

**Comment by mimooh** [comment]
> >No horsey, at least for now.
> Why do you hurt me so?
I rather thought of another image for stratagus. Stratagus is an engine
so I imagined some cog machine which was trapping Sir Stratalot's coat.

-- 
Karol Kreński

**Comment by mimooh** [comment]
Seems like a member cannot initialize the site. It needs to be done via 'Settings' button, which I don't have, so @timfel, you need to go thru 5 steps in this creator: https://pages.github.com/

**Comment by mimooh** [comment]
So, since stratagus is an engine, I also have such an idea: http://www.inf.sgsp.edu.pl/~mimooh/stratalot.svg

**Comment by DinkyDyeAussie** [comment]
That is sooo cool. Love that pic mimooh!

**Comment by mimooh** [comment]
Thx @DinkyDyeAussie :) I will enhance the latest image. And you will love the new website.

**Comment by timfel** [comment]
@mimooh you should have admin access now :)

**Comment by mimooh** [comment]
Thanks @timfel. I tweaked the logo and the site is launched at http://wargus.github.io/ and now we can add content. I guess we are going to advertise v2.4 once it's mature, so we are not in much hurry.

**Comment by mimooh** [comment]
There's no php on github pages. Including common menus or similar html processing can be done by some templating Jekyll technology, which I don't know. For now I would just go with simple html, because we don't expect more than 10 pages on that website, right?

**Comment by Kintobor** [comment]
Can you do that last one with the Stratagus text next to the gear hopping Stratalot?

**Comment by DinkyDyeAussie** [comment]
Website looks great :) Very clean. Even though it's early days I hope this type of look and functionality continues when it gets up to full speed.

**Comment by mimooh** [comment]
@Kintobor, for a horizontal banner? https://github.com/Wargus/Wargus.github.io/blob/master/img/stratagus_horiz.svg. You know you shouldn't use that bad stratagus.com! :)

@DinkyDyeAussie, I am a minimalist and I'd like a light site

**Comment by mimooh** [comment]
Since I value simplicity, this has always concerned me: wouldn't it be better to somehow merge wargus and stratagus for the installation? I know that historically these two were always distinct, I know there can be multiple games and one engine, but from regular humans perspective that are about to install it? Wyrmsun somehow managed to merge it, right? And how many games do actually work? Isn't it only wargus and aleona?

Also, I know what these two are, but I often end up installing both stratagus and wargus simultaniously. Seldom wargus only.

**Comment by Kintobor** [comment]
I agree that the Stratagus binary should be included with the Wargus install.

mimooh, when I get time I'll forward the Wargus link on Stratagus.com to your Github page.

**Comment by Andrettin** [comment]
What a lawyer posted here doesn't look very good:
https://www.reddit.com/r/gamedev/comments/4606zy/seventeen_hours_of_travel_ahead_of_me_plane_has/d01mr01

According to him, things like Wargus infringe on copyright, even though they don't directly use the install. This could be problematic for the Wargus developers (timfel is the only one remaining AFAIK).

**Comment by mimooh** [comment]
Thanks @Kintobor for the link transfering and for your agreement on the installation approach. @Andrettin, that is sad, but it's just some opinion as I understand. If some lawyers don't like wargus and they send some letters, we just ask the FSF what can be done about it, right? FSF has lawyers too, perhaps for exactly such scenarios.

**Comment by mimooh** [comment]
I am not sure I understand correctly licenses for these game assets:
http://www.turbosquid.com/3d-models/medieval-buildings-lwo/362451
http://www.turbosquid.com/3d-models/3d-castle-construction-set/351435

They are very high quality. Is it that anyone can buy these 3D objects, process them and redistribute as png with whatever games he makes? That would be cheaper than I thought. Still quite a bit for the whole game assets pack though...

**Comment by DinkyDyeAussie** [comment]
I had a pretty strong feeling that someone would pipe up again about the whole wargus thing and the use of assets from the original game.

In all honesty I don't know why blizzard didn't remake all these games (warcraft 1/2 and Star Craft 1) in higher fidelity 2D.

Their 3D engines before StarCraft II sucked imho, and I hope that the remakes they are doing now for the games I mentioned above are either 2D with awesome graphics and the same interface for all those

**Comment by DinkyDyeAussie** [comment]
*continued

people that love the nostalgia of the originals, or using the StarCraft 2 or newer engine as they are a bit better.

If you guys do want original content in terms of buildings I can use 3dsmax to model some. I would do it for free so noone is out of pocket too. 

Stratagus and Wargus are great games and I love playing.

**Comment by mimooh** [comment]
Sorry if I touched some toppic that was not to be touched :) I don't really think I would like to play with any other assets that we can buy or make ourselves - it was just that I was imaging which way I would go some day when playing with warcraft graphics was not possible. One thing is I like fantasy themes and also that I put attention to graphics quality. And warcraft gfx is just second to none!

**Comment by DinkyDyeAussie** [comment]
Yeah I understand man. I think warcraft graphics are great too!

**Comment by a-detiste** [comment]
> What a lawyer posted here doesn't look very good:

Back then, what used Blizzard to struck FreeCraft & Bnetd was _trademarks_, not _copyright_.
Now FreeCraft is the name of some MineCraft thingy & they didn't care at all about this new FreeCraft or even MineCraft (it's "*craft" something too); so it's can considered defenitively too late if they want to enfore their trademark this way again.

Copyright-wise, Wargus is 100% clean; it well shares some proprery names (name of units etc...) but this is considered an API and can't be copyrighted.

BTW, Debian lawyers thinks it safe to ship in 'contrib' engines for tens of non-free game engine re-creation for about like 15 years, biggest being ScummVM... so it should be ok :smile:

**Comment by a-detiste** [comment]
> I think warcraft graphics are great too!

Voice acting was excellent too, even in the dubbed French version for example.

**Comment by DinkyDyeAussie** [comment]
Voice acting was very good haha, so much humor I love it :) So original too. Not too many games (at least non that I've played, have that sort of humor, that I am aware of anyway. Probably wrong :P

**Comment by Andrettin** [comment]
>Back then, what used Blizzard to struck FreeCraft & Bnetd was trademarks, not copyright.

Yes, true, which is why I never thought of that before.

>BTW, Debian lawyers thinks it safe to ship in 'contrib' engines for tens of non-free game engine re-creation for about like 15 years, biggest being ScummVM... so it should be ok :smile:

Ah, since you mention that Debian lawyers have thought it safe to do that, then yes, it's probably fine.

**Comment by mimooh** [comment]
The website about Wargus and Stratagus is ready. Let me know if you find something that should be changed / improved.
http://wargus.github.io/

**Comment by DinkyDyeAussie** [comment]
Love it!

**Comment by hasufell** [comment]
The releases on github are currently confusing and don't contain useful tags. Keep in mind that source distros will want to rely on statically tagged source tarballs. `Visual Studio Dependencies` with a download  archive that is called `2015-30-11.tar.gz` doesn't meet those requirements. Can we expect proper releases/tags on github?

**Comment by timfel** [comment]
@hasufell yes, there will be proper release tags, besides the "nightly" releases. These tags will then include all the (then) current dependencies and fixed versions of the source and builds.

**Comment by timfel** [comment]
We're now testing the new release pipeline. 2.4.1 was released, but we found some issues in how we handle releases, so we're updating the code to make releasing easier. Hopefully, with more automation in that respect, we can have releases more frequently.
