### ISSUE TITLE
Ai Breaks if Build Location Becomes Invalid

### ISSUE THREAD

**Issue by Kintobor** [Wargus/stratagus#185]
If an AI goes to build a structure, and another unit blocks the build location, the AI wont attempt to build it again.

**Comment by Andrettin** [comment]
That's quite strange... I looked into the code of when an AI fails to build, but I didn't find any flaws yet.

**Comment by abenedic** [comment]
I am sorry if this is a simple question, but has anyone verified this issue on a current build?

**Comment by timfel** [comment]
I haven't seen this occur in current builds. Closing
