### ISSUE TITLE
Question about sound effects

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#195]
Trolling the sourcecode again. This time I am looking for the code that controls the sound of when you click buttons in wargus/wyrmsun/every onther stratagus-based game.

I have noticed a slight delay in the playback of the "click" sound whenever you click a button or icon. Is there a way to get rid of the delay? I tested the original Warcraft 2 BattleNet edition and there is NO delay at all.

That's all for now.

**Comment by DinkyDyeAussie** [comment]
Don't worry I found it! Woo! I'll update the trunk shortly.

**Comment by DinkyDyeAussie** [comment]
OK so I managed to get rid of the delay when clicking the icons, but now when I hold the left mouse button down on the icon it rapidly repeats the "click" sound. Just need a bit of help with this.

**Comment by Andrettin** [comment]
Hmm, could you show the code you've modified?

**Comment by DinkyDyeAussie** [comment]
Yeah mate sure can.

OK so this is the code for `ImageButton` from the trunk in `widgets.h` - unmodified


```
class ImageButton : public gcn::Button
{
public:
	ImageButton();
	explicit ImageButton(const std::string &caption);

	virtual void draw(gcn::Graphics *graphics);
	virtual void adjustSize();

	void setNormalImage(gcn::Image *image) { normalImage = image; adjustSize(); }
	void setPressedImage(gcn::Image *image) { pressedImage = image; }
	void setDisabledImage(gcn::Image *image) { disabledImage = image; }

	gcn::Image *normalImage;
	gcn::Image *pressedImage;
	gcn::Image *disabledImage;
};
```

this is my code
```

class ImageButton : public gcn::Button
{
public:
	ImageButton();
	explicit ImageButton(const std::string &caption);
	virtual void draw(gcn::Graphics *graphics);

	virtual void mousePress(int x, int y, int button);
	virtual void mouseRelease(int x, int y, int button);
	virtual void mouseClick(int x, int y, int button, int count);
	virtual void adjustSize();

	void setNormalImage(gcn::Image *image) { normalImage = image; adjustSize(); }
	void setPressedImage(gcn::Image *image) { pressedImage = image; }
	void setDisabledImage(gcn::Image *image) { disabledImage = image; }

	gcn::Image *normalImage;
	gcn::Image *pressedImage;
	gcn::Image *disabledImage;
	bool mMouseDown;
};
```
Now for the stock `ImageButton` code in `widgets.cpp` from the trunk.

```
/**
**  ImageButton constructor
*/
ImageButton::ImageButton() :
	Button(), normalImage(NULL), pressedImage(NULL),
	disabledImage(NULL)
{
	setForegroundColor(0xffffff);
}

/**
**  ImageButton constructor
**
**  @param caption  Caption text
*/
ImageButton::ImageButton(const std::string &caption) :
	Button(caption), normalImage(NULL), pressedImage(NULL),
	disabledImage(NULL)
{
	setForegroundColor(0xffffff);
}

/**
**  Draw the image button
**
**  @param graphics  Graphics object to draw with
*/
void ImageButton::draw(gcn::Graphics *graphics)
{
	if (!normalImage) {
		Button::draw(graphics);
		return;
	}

	gcn::Image *img;

	if (!isEnabled()) {
		img = disabledImage ? disabledImage : normalImage;
	} else if (isPressed()) {
		img = pressedImage ? pressedImage : normalImage;
	} else if (0 && hasMouse()) {
		// FIXME: add mouse-over image
		img = NULL;
	} else {
		img = normalImage;
	}
	graphics->drawImage(img, 0, 0, 0, 0,
						img->getWidth(), img->getHeight());

	graphics->setColor(getForegroundColor());

	int textX;
	int textY = getHeight() / 2 - getFont()->getHeight() / 2;

	switch (getAlignment()) {
		case gcn::Graphics::LEFT:
			textX = 4;
			break;
		case gcn::Graphics::CENTER:
			textX = getWidth() / 2;
			break;
		case gcn::Graphics::RIGHT:
			textX = getWidth() - 4;
			break;
		default:
			textX = 0;
			Assert(!"Unknown alignment.");
			//throw GCN_EXCEPTION("Unknown alignment.");
	}

	graphics->setFont(getFont());
	
	bool is_normal = true;
	
	if (hasMouse()) {
		is_normal = false;
	}

	if (isPressed()) {
		graphics->drawText(getCaption(), textX + 4, textY + 4, getAlignment(), is_normal);
	} else {
		graphics->drawText(getCaption(), textX + 2, textY + 2, getAlignment(), is_normal);
	}

	if (hasFocus()) {
		graphics->drawRectangle(gcn::Rectangle(0, 0, getWidth(), getHeight()));
	}
}

/**
**  Automatically adjust the size of an image button
*/
void ImageButton::adjustSize()
{
	if (normalImage) {
		setWidth(normalImage->getWidth());
		setHeight(normalImage->getHeight());
	} else {
		Button::adjustSize();
	}
}
```
...and now my modified code
```

// Dinky Begin
/**
**  ImageRadioButton constructor
*/
ImageButton::ImageButton() : Button(), 
	normalImage(NULL), pressedImage(NULL), disabledImage(NULL),
	mMouseDown(false)
{
	setForegroundColor(0xffffff);
}
// Dinky End

/**
**  ImageButton constructor
**
**  @param caption  Caption text
*/
ImageButton::ImageButton(const std::string &caption) : gcn::Button(caption), 
	normalImage(NULL), pressedImage(NULL), disabledImage(NULL),
	mMouseDown(false)
{
}

/**
**  Draw the image button
**
**  @param graphics  Graphics object to draw with
*/
void ImageButton::draw(gcn::Graphics *graphics)
{
	bool is_normal = true;
	if (hasMouse())
	{
		is_normal = false;
	}

	if (!normalImage) {
		Button::draw(graphics);
		return;
	}

	gcn::Image *img;

	if (isEnabled() == false) 
	{
		img = disabledImage ? disabledImage : normalImage;
	} 
	else if (mMouseDown)
	{
		img = pressedImage ? pressedImage : normalImage;
	} 
	else if (0 && hasMouse()) 
	{
		// FIXME: add mouse-over image
		graphics->setColor(ColorYellow);
		graphics->drawRectangle(gcn::Rectangle(0, 0, getWidth() - 1, getHeight() - 1));		
	} 
	else 
	{
		img = normalImage ? normalImage : normalImage;
	}

	graphics->drawImage(img, 0, 0, 0, 0, img->getWidth(), img->getHeight());

	graphics->setColor(getForegroundColor());

	int textX;
	int textY = getHeight() / 2 - getFont()->getHeight() / 2;

	switch (getAlignment()) {
		case gcn::Graphics::LEFT:
			textX = 4;
			break;
		case gcn::Graphics::CENTER:
			textX = getWidth() / 2;
			break;
		case gcn::Graphics::RIGHT:
			textX = getWidth() - 4;
			break;
		default:
			textX = 0;
			Assert(!"Unknown alignment.");
			//throw GCN_EXCEPTION("Unknown alignment.");
	}

	graphics->setFont(getFont());

	if (mMouseDown) {
		graphics->drawText(getCaption(), textX + 4, textY + 4, getAlignment(), is_normal);
	} else {
		graphics->drawText(getCaption(), textX + 2, textY + 2, getAlignment(), is_normal);
	}

	if (hasFocus()) {
		graphics->drawRectangle(gcn::Rectangle(0, 0, getWidth() - 1, getHeight() - 1));
		graphics->setColor(ColorYellow);
	}
}

/**
**  Mouse button pressed callback
*/
void ImageButton::mousePress(int, int, int button)
{
	if (button == gcn::MouseInput::LEFT && hasMouse()) {
		mMouseDown = true;
		PlayGameSound(GameSounds.Click.Sound, MaxSampleVolume);
	}
}

/**
**  Mouse button released callback
*/
void ImageButton::mouseRelease(int, int, int button)
{
	if (button == gcn::MouseInput::LEFT) {
		mMouseDown = false;
	}
}

/**
**  Mouse clicked callback
*/
void ImageButton::mouseClick(int, int, int button, int count)
{
	if (button == gcn::MouseInput::LEFT) 
	{
		generateAction();
	}
}

/**
**  Automatically adjust the size of an image button
*/
void ImageButton::adjustSize()
{
	if (normalImage) 
	{
		setWidth(normalImage->getWidth());
		setHeight(normalImage->getHeight());
	} 
	else if (pressedImage)
	{
		setWidth(pressedImage->getWidth());
		setHeight(pressedImage->getHeight());
		Button::adjustSize();
	}
}
```

To get the buttons to work right I had to change a couple of the `isPressed()` over to `mMouseDown`. So far it all works, apart from the icons clicking constantly when you hold the mouse button down on them for a long time. That's the only gripe I am having so far.

Also how would I make a menu button to be the "default" button. In the original game there was always a "default" button that whenever you pressed enter it would automatically perform the action of the default button. Like in the Game menu "Return to Game" would be the default button, and when you pressed enter you would return to the game.

How could I do that?

**Comment by DinkyDyeAussie** [comment]
So I have found what is causing the click sound to repeat when you hold the mouse button down on the icon...

```
		if (flags & IconClicked) { // Shift the icon a bit to make it look like it's been pressed.
			**PlayGameSound(GameSounds.Click.Sound, MaxSampleVolume);**
			DrawUIButton(&s, flags, pos.x + 1, pos.y + 1, text, player);
			if (flags & IconSelected) {
				Video.DrawRectangle(ColorGreen, pos.x + 1, pos.y + 1, 46, 38);
			}			
			Video.DrawRectangle(ColorGray, pos.x, pos.y, 48, 40);

			Video.DrawVLine(ColorDarkGray, pos.x - 1, pos.y - 1, 40);
			Video.DrawHLine(ColorDarkGray, pos.x - 1, pos.y - 1, 49);
			Video.DrawHLine(ColorDarkGray, pos.x - 1, pos.y + 39, 2);

			Video.DrawRectangle(ColorGray, pos.x - 4, pos.y - 4, 54, 46);
		} else {
			DrawUIButton(&s, flags, pos.x, pos.y, text, player);
			if (flags & IconSelected) {
				Video.DrawRectangle(ColorGreen, pos.x, pos.y, 46, 38);
			}
		}
```
I put the code to play the sound whenever you click the icon. But, hold the mouse button down over the icon too long and the sound repeats. I've been trying to think of what type of loop I could use to test whether the sound has already played once, but I can't figure it out. I tried a `while loop` and that froze the game. I thought of using a `for loop` but couldn't think of what to write.

I love tweaking this stuff, but would like a hand if you can help 👍

**Comment by timfel** [comment]
I don't understand the problem and I don't see your changes. Can you open a branch or point me to one where you see the problem?

**Comment by DinkyDyeAussie** [comment]
With the unmodified code, whenever you "click" a button in wargus, the "click" sound effect doesn't play straight away, there is a noticeable delay. In warcraft 2 however, the click happens literally as soon as you press the mouse button down on a button.

I am simply trying to get rid of the delay in the playing of the sound. I haven't been able to get rid of the sound repeating though when you hold the mouse button down on an icon or button. This is what I am trying to figure out atm with no luck. Just looking for some guidence.

BTW the line in the code with the arrow - -----> , is where the code is to play the sound when you click the icon. I am just trying to make it so the sound plays once, regardless of whether you click, or hold the mouse down, and won't loop.

**Comment by Andrettin** [comment]
The delay probably happens because the sound is being played when you "let go" of the button, instead of when you press it?

**Comment by DinkyDyeAussie** [comment]
Yes it did that originally Andrettin, but I added it to the mouseDown event in the ImageButton and Icon Border events and it made it so it plays when you click it instead of when you let it go and there is still a small delay that I am trying to figure out (with no luck) how to get rid of.

**Comment by timfel** [comment]
This had to be fixed in multiple places: the buttonpanel code already reacted on mouse down, but not all paths correctly played the mouse click sound. Second, instead of adding sound code to the image button widget (which is just architecturally wrong imo) I made the LuaActionCallback also usable for mouse and key events. The "click" sound in wargus for image buttons is defined in Lua code anyway, it was attached to the action callback, which runs when the button is released. Now in wargus lua code, we also listen on the mouse down event to play the click sound.

The changes give you two click sounds if you press - hold for a second - and release. which i think is fine, it acknowledges the down and then the action. If you just click normally, only one of the samples is actually played (the one on mouse down).

Another minor tweak was to reduce the buffer size for sounds, so that the sound starts playing sooner rather than loading into the soundbuffer first
