### ISSUE TITLE
Constant Console output dump.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#199]
A Bug results in a Constant Console output dump. Stratagus posts this to the console on an almost constant basis.

eTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of ran*** Error in `../stratagus/build/stratagus': free(): invalid pointer: 0x0000000003a72f40 ***
ge. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -4, x: 5, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 26, pos: -7, x: 6, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of

**Comment by mimooh** [comment]
Never saw that. What OS, what version of wargus/stratagus?

**Comment by Zombie-Ryushu** [comment]
Stratagus v2.4.1-gitfbc7485d976efa25c58fa5f41e99ebf86216cdc2

Wargus is the latest Checkout, this is on Linux

**Comment by Zombie-Ryushu** [comment]
19982016
