### ISSUE TITLE
Poor AI Enemy Finder Performance

### ISSUE THREAD

**Issue by Andrettin** [Wargus/stratagus#200]
The AI enemy finder uses BestTargetFinder to get an enemy, but that leads to poor performance, as the latter tries to calculate a path to every enemy unit evaluated. Which in the case of the AI enemy finder, includes the entire map! It makes sense to use the BestTargetFinder for short-range finding, but for long-range finding IMO it would be better to use a terrain traversal. I have implemented a terrain traversal for AI enemy finding in Wyrmgus, here is the relevant commit:

https://github.com/Andrettin/Wyrmgus/commit/ff4a29a1b813cca8e0d9858c66ee2c617aa756df

Note: for Stratagus you will likely want to remove the check to see if the position is explored, as it doesn't have AI exploration. The "attackrange" variable should use the unit type's stats rather than the function it uses there, which exists only in Wyrmgus. Additionally, the "includes_neutral" isn't necessary, as in Stratagus the AI doesn't search for non-enemies (who are also non-allies) to declare war to if it has no enemies.

**Comment by timfel** [comment]
I finally got around to look at it :) Thanks for that, and also the list of things to watch out for :) The only additional thing I removed were the `unit.MapLayer` references. https://github.com/Wargus/stratagus/pull/243

**Comment by Andrettin** [comment]
Great, I'm happy to have helped :)
