### ISSUE TITLE
Issue with unit_find.cpp

### ISSUE THREAD

**Issue by Andrettin** [Wargus/stratagus#202]
These lines in unit_find.cpp (which was implemented with the changes in early 2016) seem problematic:

```
			const int x = dest->tilePos.x - attacker->tilePos.x + (size / 2);
			const int y = dest->tilePos.y - attacker->tilePos.y + (size / 2);
			Assert(x >= 0 && y >= 0);
```

The assert says that the X and Y should be non-negative. But the way the variables are set, they can easily be negative if the attacker is located to the southeast of the potential target. Specially considering that the "size" there is defined earlier as the missile's splash range.

**Comment by keithstellyes** [comment]
I would be willing to do a PR to remove the assertion, but nobody has said if the assert should be there or not.

This assert also occurs later in the code, too:

```
		x = dest->tilePos.x - attacker->tilePos.x + (size / 2);
		y = dest->tilePos.y - attacker->tilePos.y + (size / 2);
		Assert(x >= 0 && y >= 0);
```

**Comment by timfel** [comment]
It's been too long and I don't have time to dive into that code any time soon to understand what it's supposed to do. But I'm happy to accept PRs if you have time :)
