### ISSUE TITLE
fullscreen on windows doesn't take up full screen

### ISSUE THREAD

**Issue by MamiyaOtaru** [Wargus/stratagus#203]
wargus 2.4.1 with stratagus 2.4.1: fullscreen changes my monitor's resolution to the desired res, but wargus does not take up the full screen.  Can see other windows around the outside.  Alt-tabbing out and back in makes it fill the whole screen.  http://chattypics.com/files/notFull_cp9j6t9enr.png

Pretty sure it's a change in Stratagus between 2.4.0 and 2.4.1, as the issue does not happen with wargus 2.4.0 + stratagus 2.4.0, and _also_ does not happen with wargus **2.4.1** + stratagus **2.4.0**.

Happens with opengl on or off, windows scaling 125 or 100 (thought it might be the change that told windows stratagus is scaling aware, seems not the be the case though).  Occurs also with nightly stratagus exe

Win10, nvidia 970, 2560*1440 monitor res

**Comment by MamiyaOtaru** [comment]
ok, it's to do with scaling after all.  setting scaling in windows to 100% wasn't enough.  Right click, compatibility, "override high DPI scaling behavior" fixes this.  Maybe rethink that change to the manifest, I'm assuming this did it: https://github.com/Wargus/stratagus/commit/9b39ebd4b3f6f887a9aee759d55a73ef589f2798

**Comment by timfel** [comment]
Damnit, I was hoping to achieve the opposite effect with that commit. Can you revert and open a PR?

**Comment by timfel** [comment]
Besides reverting that PR, the window in windowed mode is now also resizeable, so that may make playing easier, too.
