### ISSUE TITLE
mouse unusable in fullscreen

### ISSUE THREAD

**Issue by MamiyaOtaru** [Wargus/stratagus#204]
wargus 2.4.1 + stratagus 2.4.1: mouse jumps around a lot, seems to reset to bottom right corner mainly

Pretty sure it's a change in Stratagus between 2.4.0 and 2.4.1, as the issue does not happen with wargus 2.4.0 + stratagus 2.4.0, and _also_ does not happen with wargus **2.4.1** + stratagus **2.4.0**.

Happens with opengl on or off, windows scaling 125 or 100 (thought it might be the change that told windows stratagus is scaling aware, seems not the be the case though). Occurs also with nightly stratagus exe

Win10, nvidia 970, 2560*1440 monitor res

Possibly related to https://github.com/Wargus/stratagus/issues/203

**Comment by MamiyaOtaru** [comment]
related to 203 after all it seems.

it's to do with scaling after all.  setting scaling in windows to 100% wasn't enough.  Right click, compatibility, "override high DPI scaling behavior" fixes this.  Maybe rethink that change to the manifest, I'm assuming this did it: https://github.com/Wargus/stratagus/commit/9b39ebd4b3f6f887a9aee759d55a73ef589f2798

**Comment by keithstellyes** [comment]
I confirm I am having the same issue (w/ stratagus 2.42 + stargus 2.41) with Windows 10 @2560*1440 res with and that @MamiyaOtaru 's workaround fix of overriding DPI scaling behavior fixing it

**Comment by DinkyDyeAussie** [comment]
Thanks Keith! Will give it a shot today.

Wow Wargus @ 1440p. Must look really nice I reckon.

**Comment by timfel** [comment]
If you could do a PR reverting the change to the manifest (if that fixes it), I'm happy to merge that.

**Comment by keithstellyes** [comment]
I'll test with that change,  but do you remember if there was an issue filed for the window stretching mentioned in its commit message?

**Comment by timfel** [comment]
I reverted that commit now, and also added a few fixes from Wyrmgus, maybe that'll help

**Comment by boypush** [comment]
I use Stratagus 2.4.2 Wargus 2.4.1 in full screen the mouse jumps into random places! Please help! How can fix that?!

**Comment by boypush** [comment]
Yes, I used the latest versions and still my mouse cursor teleports and can not be played

**Comment by boypush** [comment]
Please help, what can I do? (Windows 10 x64 last update)
