### ISSUE TITLE
Running Wargus with debug log?

### ISSUE THREAD

**Issue by ireece1** [Wargus/stratagus#208]
I was adding some custom units and i think i messed up somewhere along the lines, now Wargus will not open.

Is there anyway to see the debug output when i open it so i can see whats causing the game to crash? I'm on windows.

**Comment by timfel** [comment]
You would have stdout.txt and stderr.txt in %AppData%/Stratagus. If you run stratagus.exe with - h, it will print a short help on command line flags to those files, too.
