### ISSUE TITLE
Where is 2.4.3?

### ISSUE THREAD

**Issue by CosmeFC** [Wargus/stratagus#211]
I was unable to find it. Could you help me?

**Comment by timfel** [comment]
2.4.3 is not out yet :)

**Comment by CosmeFC** [comment]
Oh, Sorry.
I am having some problens importing/converting media files.
Do you have a release date?

What do I need to create a meta server?

--
Cosme Corrêa
Universidade Federal Fluminense - UFF
Superintendência de Tecnologia da Informação - STI
+55 21 4042-6606
+1 814 470-2300

On Sep 3, 2017 12:58, "Tim Felgentreff" <notifications@github.com> wrote:

2.4.3 is not out yet :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Wargus/stratagus/issues/211#issuecomment-326813436>,
or mute
the thread

**Comment by timfel** [comment]
Sorry for the late reply. What problems do you have with importing?

A metaserver is just a binary that comes with stratagus on Linux, you can start it and then current versions of Stratagus allow you to connect to a metaserver in the Create Multiplayer Game screen, and you can connect to a metaserver to join games, too. It mostly makes discovering games on the local network easier (or in a VPN), and only works over the internet if you're lucky.

We have a default metaserver running and advertising games. You can see it in the sidebar on https://wargus.github.io

**Comment by CosmeFC** [comment]
Hi,
thank you for you time.

What is better?
Several subjects here or create different threads?

**Comment by timfel** [comment]
Creating different threads may be better :)
