### ISSUE TITLE
2.4.2 has no music

### ISSUE THREAD

**Issue by CosmeFC** [Wargus/stratagus#212]
Hi,

I am unable to play game musics.

I am using Windows 10
Stratagus and Wargus 2.4.2
I extracted data from 2 CDs.
There ar several MIDI files inside: C:\Users\ME\AppData\Roaming\Stratagus\data.Wargus\music

**Comment by timfel** [comment]
Is this a new issue? This is surprising, but I haven't tested 2.4.2 recently, it used to work with 2.4.1

**Comment by MamiyaOtaru** [comment]
probably has something to do with 
fluidsynth: error: Unable to open file "music/TimGM6mb.sf2"
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont "music/TimGM6mb.sf2"
Copying TimGM6mb.sf2 into %appdata%\Stratagus\data.Wargus\music (it wasn't there after installation) allows music to play.  Assume it has to do with all data being in %appdata% now (new in 2.4.2?) but the soundfont didn't make it there

**Comment by timfel** [comment]
This should be fixed now, the soundfont is now also copied over into the correct location
