### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by CosmeFC** [Wargus/stratagus#213]
They are frequent.

A step description that always crash

1. Simple player Game
2. Campaign Game
3. For the motherland
4. Beachheaded

![image](https://user-images.githubusercontent.com/4854932/30392917-ab657cde-9894-11e7-924e-42ac7c06252e.png)

**Comment by timfel** [comment]
Yes, this is an issue in pur scripts, that campaign should not be available in Wargus, only with Aleonas Tales.

**Comment by Kintobor** [comment]
Everything in Aleona's Tales used be available in Wargus 2.3. It's probably going to be a simple fix.

**Comment by Kintobor** [comment]
Please deleted "/scripts/lists/campaigns/For the Motherland (Alliance)" folder. That was only for testing in Wargus 2.3.1.

**Comment by Kintobor** [comment]
This one should also get removed: "/scripts/lists/campaigns/For the Motherland (Horde)"

**Comment by Kintobor** [comment]
I just checked. AT 2.4.2 doesn't work with the two For the Motherland campaigns. However, they worked fine with my copy of Wargus 2.3.

**Comment by Kintobor** [comment]
I just checked. The two For the Motherland campaigns worked fine in Wargus 2.3. It's a shame. The Alliance FtM campaign as pretty fun.

**Comment by timfel** [comment]
I've removed the tales dataset from Wargus on master (we have a separate project for those where we can get them to run properly - https://github.com/Wargus/Timeless-Tales). The For the Motherland single player maps work, the campaign has been removed from Wargus
