### ISSUE TITLE
loading of wargus game fails

### ISSUE THREAD

**Issue by haehn** [Wargus/stratagus#217]
if i save a single player game and then later try to load it, the whole program exits and ubuntu reports a crash

what can i do? my son is mad AF since i told him save and everything is gonna be good

Ubuntu 16.04.3
Stratagus 2.4.2

**Comment by timfel** [comment]
Can you post the output when it crashes? Run `wargus` in a terminal and add a comment what it prints here.

**Comment by haehn** [comment]
Here is the output, but I don't think it is so valuable: https://pastebin.com/1WXrPkkW
However, here is are screenshots from the error dialog

![1](https://user-images.githubusercontent.com/64670/33102164-7f639a90-cee9-11e7-8441-2c1e8ace2630.png)

![2](https://user-images.githubusercontent.com/64670/33102169-82b8a992-cee9-11e7-8015-f6918045652e.png)

![3](https://user-images.githubusercontent.com/64670/33102171-85a7680a-cee9-11e7-9a61-aababa1d99eb.png)

**Comment by haehn** [comment]
we also have other random crashes since upgrading to 2.4.2

is there a way to downgrade (on ubuntu) to 2.4.1?

**Comment by haehn** [comment]
@timfel could you please take a look? we love wargus here and this is such a downer

**Comment by keithstellyes** [comment]
@haehn are you still having issues with this?

Have you tried `sudo apt-get update && sudo apt-get dist-upgrade` ? the error report is saying you have obsolete packages, else you could pull the 2.41 branch and build it yourself

**Comment by haehn** [comment]
Finally got around to compiling stratagus 2.4.1 and wargus 2.4.1 on all our machines. It runs much more stable now and all games load without any problem! Thank you! (PS: the obsolete packages error was not causing the problem)

**Comment by haehn** [comment]
downgrade to wargus 2.4.1 fixed the issue

**Comment by haehn** [comment]
commit f5b1ede is the golden one
