### ISSUE TITLE
metaserver 100% CPU usage

### ISSUE THREAD

**Issue by mimooh** [Wargus/stratagus#218]
@timfel, hi after long time :) It is second time that I log to the VPS that hosts stratagus metaserver and I can see metaserver consumes 100% CPU. One thing that this is a multiuser environment where people share single linux kernel and single CPU/memory so we should respect their needs, and second that I will start using this machine for other services.

A month ago or so I restarted such a 100% CPU metaserver and it used like almost no CPU after that. But now there's that 100% usage again. Can we do somehting about it? As a starter I could just have a cron job restarting it every evening, or more often if needed -- would I just copy the metaserver to my folder and run 

    ./metaserver

as mimooh? Or what better ideas do you have?

**Comment by timfel** [comment]
Hi, sure, I wanted to investigate resource usage for a while, but I don't have the time right now. If you could just set up a cron job to restart it, that would work for now, just starting the binary in a folder where it can write a DB file is enough. Thanks, please keep this issue open so I don't forget to investigate when I find the time.

From: Karol Kreński
Sent: Saturday, 16 December, 15:39
Subject: [Wargus/stratagus] metaserver 100% CPU usage (#218)
To: Wargus/stratagus
Cc: Tim Felgentreff, Mention


@timfel<https://github.com/timfel>, hi after long time :) It is second time that I log to the VPS that hosts stratagus metaserver and I can see metaserver consumes 100% CPU. One thing that this is a multiuser environment where people share single linux kernel and single CPU/memory so we should respect their needs, and second that I will start using this machine for other services.
A month ago or so I restarted such a 100% CPU metaserver and it used like almost no CPU after that. But now there's that 100% usage again. Can we do somehting about it? As a starter I could just have a cron job restarting it every evening, or more often if needed -- would I just copy the metaserver to my folder and run
./metaserver
as mimooh? Or what better ideas do you have?

**Comment by timfel** [comment]
We're removing metaserver in favor of battle.net protocol support and using one of the open bnet servers.
