### ISSUE TITLE
Mouse is teleporting in all Stratagus Mods on Win 10 1709

### ISSUE THREAD

**Issue by Peacemaker80** [Wargus/stratagus#219]
Hello,
i am not sure, if this problem is correct posted at the wargus repository. So i will post it here too.

My wargus installation works fine since 1 year with windows 10 Home 1703. Today my system installed Fall Update 1709 and the mouse teleports starts also on my warguis installation. It teleports also with war1gus. It teleports randomly the cursor from my focused unit to one corner or to the top or to the bottom. So it seems to be a problem with stratagus and windows 10 ver1709. The guys working on the project CNCNet have had the same poblem and fixed it. https://forums.cncnet.org/topic/7898-windows-10-fall-creators-update-issues/ with disable windowing mode. 
I tested also the windows dpi overwrite function but nothing works. Its very frustrating.
Does anybody have another idea or workaround?

**Comment by timfel** [comment]
I applied a few fixes from @Andrettin, maybe that'll help.

**Comment by timfel** [comment]
Should be fixed in trunk, according to some other reports on other issues
