### ISSUE TITLE
Can you upload "dependences" folder to Stratagus source code please?

### ISSUE THREAD

**Issue by pasildan** [Wargus/stratagus#221]
I hope some developer can read this, but I have been looking to compile Stratagus, however it's not possible because it requires a folder called as " dependences " and there is no such folder in source code.

Would appreciate if some developer or anyone can upload again all the source including dependences folder or any other folder required to compile it.

Would appreciate it a lot.

**Comment by timfel** [comment]
I guess you're trying to compile on Windows. The dependencies are not part of Stratagus, you have to either a) download and build them yourself or b) try to use pre-built binaries from our releases (https://github.com/Wargus/win32-stratagus-dependencies/releases). If you need to build yourself, you can try to clone and build https://github.com/Wargus/win32-stratagus-dependencies. Also, the `dependencies` folder is really just a default, you have to tell it where the dependencies are.
