### ISSUE TITLE
Significant wait time during game loading

### ISSUE THREAD

**Issue by lacombar** [Wargus/stratagus#223]
When starting a game, there is a significant wait time, measured up to 20s, with no screen update and 100% CPU usage. Doing a quick profiling in XCode Instruments show that all that time is being spend in `ShowLoadProgress() -> RealizeVideoMemory() -> SDL_UpdateRects()` even though `stratagus` was configured to use OpenGL.

Accordingly, turning `ShowLoadProgress()` in an no-op leads to an instantaneous game loading.

**Comment by timfel** [comment]
I've disabled the forcing to screen on every load, instead it only shows it every 500ms. On most machines these days that means it'll just go straight into the game, on my rpi1 it shows exactly one load
