### ISSUE TITLE
Wargus 2.4.2 + OpenGL = No videos, just music

### ISSUE THREAD

**Issue by 2mg** [Wargus/stratagus#229]
On Windows 7 x64 SP1 @720p, only music plays during cinematics.

Turning off OpenGL fixes it, but the game is wonky without it and I'd rather play with this option turned on. 
Another workaround is to switch to windowed mode...

PS: Why is the video quality so bad? I ran them from "videos" folder in VLC, the quality is very bad.

**Comment by DinkyDyeAussie** [comment]
I find the using OpenGL gives me an error with the 'data.Wargus' directory. The game says I should remove that directory, but when I use standard rendering - SDL - it's fine - I get music and everything. I don't know what OpenGL bug is causing all this but it hasn't been there until recently.

**Comment by 2mg** [comment]
Wargus seems to leave a lot in /user/appdata/roaming/stratagus, so if you have issue and wanna do a reinstall/try other versions, make sure you DELETE it all. The "remove configuration" option in uninstaller doesn't help much.

**Comment by DinkyDyeAussie** [comment]
I did a full re-install. It hasn't stopped the OpenGL error, but I do get all the music working and everything else works fine too. It's just the OpenGL issue. Something to do with the TimGM6mb.sf2 sound font file not being there. Even though I tried copying it into the directory. No luck.

**Comment by 2mg** [comment]
I'm on 2.4.1 if it matters.

**Comment by timfel** [comment]
We've migrated to SDL2 and away from the legacy OpenGL + SDL1 API on the latest master. With SDL2 this should not happen anymore since the entire codepath is rewritten. We'll get a new release with SDL2 out shortly.
