### ISSUE TITLE
Wargus/Stratagus 2.4.2 - Failed to load the SoundFont: music/TimGM6mb.sf2

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#230]
Failed to load the SoundFont: music/TimGM6mb.sf2

I only EVER get the message for this when I use OpenGL. It never occurs when I use SDL. I have copied the TimGM6mb.sf2 file to the 'data.Wargus/music' folder and it still gives the error.

I have to manually change the setting back to SDL in the preferences file in the '%appdata%/Roaming/Stratagus' folder.

I might have a look through the wartool source code and see what it's doing when it extracts this particular file.

**Comment by timfel** [comment]
We've migrated to SDL2 on master, and the sound and graphics code was replaced with SDL2_mixer and SDL2_image for better maintainability. The soundfont is not needed anymore, since the SDL2_mixer library takes care of midi support for us now
