### ISSUE TITLE
Metaserver should create dedicated hosts

### ISSUE THREAD

**Issue by DanielHartl** [Wargus/stratagus#232]
I think we should redefine the role of metaserver. Additionally to just enable discovery of newly hosted games it should actually start the dedicated server instances and register them with itself to allow clients to discover and connect to it. We could use a WebUI that allows people to create new games.

In combination with my latest changes of using TCP, this would make playing online games much more user friendly.

**Comment by timfel** [comment]
The metaserver is being removed in favor of battle.net protocol compatibility. On the tim/pvpgn branch this allows us to start online games and connect. In some instances it will need port forwarding setup (like classic WC2 and Diablo), but different to those games we also try to establish a connection using UDP hole punching, which in my testing works well for the common type of private routers people have at home. It doesn't work for enterprise networks, but that's the same issue for Diablo and WC2, and we can deal with that at a later stage, by merging your migration to TCP
