### ISSUE TITLE
code::blocks and stratagus

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#235]
I have been trying to move away from Visual Studio, because I cannot afford it and I want to try and get as much free dev softeware as possible, so I am using code::blocks now. 

My problem is, even though CMAKE created the project files for code::blocks, the project isn't successfully compiling. I am using MinGW as the complier and have tried both the 32 and 64-bit compilers, with no luck.

I have also tried using the SDL libraries from both mingw download off the SDL site and also the MSVC libraries....Honestly what the hell is this 'libSDL2.a' stuff? MinGW does things waaaay different.

![codeblocks error](https://user-images.githubusercontent.com/15978175/44633210-4ff96600-a9cb-11e8-9cee-abb06446ccdd.png)

These are the errors I am getting in codeblocks when I compile.

**Comment by timfel** [comment]
Since you now got it working with VS, closing this
