### ISSUE TITLE
Getting linking errors in MSVC 2015

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#236]
Two lots of errors. I have made sure all the directories are included and I am sure the library options are all defined in the linker, but maybe you guys can point something out that I might be missing.

![msvc error 1](https://user-images.githubusercontent.com/15978175/44658956-f7b37a00-aa45-11e8-9139-859fe8e5f280.png)

![msvc error 2](https://user-images.githubusercontent.com/15978175/44658957-f8e4a700-aa45-11e8-9dc9-7ce7060cdf2a.png)

I am so close but really need some help. Also I can't find the 'fluidsynth.h' file anywhere...even though there is a cpp version.

**Comment by Andrettin** [comment]
@DinkyDyeAussie Check out this commit I made for Wyrmgus to fix compilation under VS2017:
https://github.com/Andrettin/Wyrmgus/commit/d219caa11c761194911f84854be67d346d24a4ee#diff-d8086a99c56f22e175f2bd49a2943d86
