### ISSUE TITLE
Launch Error - Lua - attempt to index a nil value (global 'table')

### ISSUE THREAD

**Issue by Nassiel** [Wargus/stratagus#239]
Hello,

I downloaded and compiled the master branch in a `fedora 28: 4.18.14-200.fc28.x86_64`. The `lua version is 5.3.4`.

After some tries without any success I compiled it again in debug mode, then I debugged the code of stratagus with the next arguments "wargus -d ~/.stratagus.data.Wargus/" and in the end I receive the next error:
`[string "~/.stratagus/data.Wargus/scripts/stratagus.lua"]:59: attempt to index a nil value (global 'table')`
 
As you see, It happens at the very beginning while calling the LoadCcl function. I don't know what to do know to solve it. I don't know if you have a method to debug lua which includes all the initialization parameters that stratagus launches. Because I tried with mobdebug to load with require (not allowed) to just Load the script, not working either.

Thanks!

**Comment by Nassiel** [comment]
Do you have any plan to update to 5.3 or will you accept that development?

**Comment by Nassiel** [comment]
Understood, yeah I was talking a look about that fork, and apart it's not official with just with this message "The patch might be incomplete at this time. Use at your own risk!" I had enough.

The main problem I see is that stratagus depends too much on the SO and it's not very easy to keep both versions of lua at the same time. Did you evaluate the idea of add internally the lua 5.1 code?

**Comment by timfel** [comment]
Those PRs were merged, closing this.
