### ISSUE TITLE
Compiling in Visual C++ 2017 issues

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#245]
I am having these errors. This is all that is left before it hopefully compiles successfully. I need some help identifying what I need to do to get it to work properly.
![compile](https://user-images.githubusercontent.com/15978175/56890940-352d4300-6abe-11e9-9d6e-42b9e9ec1527.png)

**Comment by timfel** [comment]
I have now idea, but is the project maybe set to Console Application? It should be Win32 application or something to that. But cmake should generate the right type automatically...

**Comment by DinkyDyeAussie** [comment]
I will check that out later today. If that is all it is then hopefully it will all work.

Also, how many of the win32 dependencies do I actually need? Quite a few of them don't have a CMakeList.txt and I am not sure how I am meant to compile them.

Which compiler/s do I need to obtain to compile all the libraries?

**Comment by timfel** [comment]
The libraries you want are all in our win32-dependencies repo. There's a build script that works on VS2015 32bit. On the releases page of that repo there are prebuilt zip files with all of the dependencies. Check out our appveyor.yml file in Stratagus to see how to tell Cmake to use that bundle
________________________________

**Comment by DinkyDyeAussie** [comment]
So I downloaded the Win32 libs from the repo and ran CMAKE - smoothest ever CMAKE session, didn't change a thing and it found the lib files straight away. I then opened the project in Visual studio and added a few include/library directories just to make sure it knew where it all was, and it compiled first time!

Thanks Tim. You're a legend :)

**Comment by DinkyDyeAussie** [comment]
I redact that last statement. I have gone from 2.4.1 game and sourcecode to the 'master-branch' "bleeding edge" builds and am back at square one.

![code](https://user-images.githubusercontent.com/15978175/57014704-8ff8a300-6c54-11e9-8ac9-87530633564e.png)

I have the master build versions of the sourcecode, game and the win32 dependencies. I regenerated the sourcecode in CMAKE and then opened it in Visual Studio and once I set everything up and compile, this happens...

...help. please :(

**Comment by timfel** [comment]
We updated to VS2019 on appveyor and realized you have to explicitly tell cmake now to create win32 binaries. Otherwise it will just give you linkage errors with our dependencies. So the fix is to use something like `cmake -G "Visual Studio 16 2019" -T v141_xp -A win32`
