### ISSUE TITLE
How do you slow down the Colorcycling?

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#246]
I know where it is in the sourcecode. Tried changing the divider number and even the division to multiplication, with no slowdown at all in game.

The original used to be slower when cycling the colours. If it is tied to game speed then I will try to see where that it in the sourcecode.

Just thought I would ask.

**Comment by timfel** [comment]
It's defined as a fixed number in `video.cpp`
```
#define COLOR_CYCLE_SPEED  (CYCLES_PER_SECOND / 4)
```

**Comment by DinkyDyeAussie** [comment]
Yes, that's the one I changed but it didn't do anything. I made sure to check I was using the correct stratagus executable once it was compiled but there was no difference. I swear it used to make a difference before wargus data got extracted to the appdata stratagus folder.

**Comment by timfel** [comment]
I just tried and it definitely works. For example, changing it to this:
```
#define COLOR_CYCLE_SPEED  (CYCLES_PER_SECOND * 10)
```
makes it go super slow.

**Comment by timfel** [comment]
I have no idea what the "right" speed would be, so I'm not going to change anything, feel free to open a pull request once you figure it out and I'll merge it

**Comment by timfel** [comment]
> I swear it used to make a difference before wargus data got extracted to the appdata stratagus folder.

That's impossible, this value is compiled into stratagus, there's no connection to where the data is.

**Comment by DinkyDyeAussie** [comment]
It worked. Turns out I was copying the Stratagus binary to the wrong folder lol.

**Comment by timfel** [comment]
Hey @DinkyDyeAussie, since you figured this out, do you have a patch to make the speed as in the original?

**Comment by DinkyDyeAussie** [comment]
I'll find it and ass the code to the repository.

**Comment by timfel** [comment]
Since the fix is now merged to master, I'm closing this
