### ISSUE TITLE
Archer attacking units at greater distance than "MaxAttackRage"

### ISSUE THREAD

**Issue by timfel** [Wargus/stratagus#25]
Was playing through human 04 in the tides of darkness campaign, and noticed that when I used an archer to attack an orc transporter, he attacked the boat even though the boat was halfway down the map. This is way more than "MaxAttackRange" allows normally.

Just letting ppl know so it can be fixed...

---

Imported from Launchpad using lp2gh.
- date created: 2015-02-25T04:30:37Z
- owner: dinky-dye-aussie
- assignee: iddqd-mail
- the launchpad url was https://bugs.launchpad.net/bugs/1425381

**Comment by timfel** [comment]
(by iddqd-mail)
I need the replay for this game (if you haven't saved it, it could be found as the last modified file in /wc2/logs folder)

**Comment by abenedic** [comment]
Is this still an issue on a current version ~ 2020 or later?

**Comment by timfel** [comment]
I tried to reproduce this in 2017 or 2018 for some time and couldn't. Since there's been no such report since, closing
