### ISSUE TITLE
Wrong coordinates for Patrol order when ordered via queue (shift + order)

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#268]
When we put "patrol" order in the orders queue (shift + order) it will get wrong coordinates. Instead of coordinates for previous order in queue, it will be use current unit coordinates.

in case:  `press_Shift -> RClick_to_point1 -> RClick_to_point2 -> ('p'+LClick_point3)->release_Shift`
Patrol will be ordered from `point3` to `point_where_the_unit_is_now` in the moment of making queue.
Must be between `point2` and `point3`

**Comment by mxdamien** [comment]
Hi !

Can't confirm this. 
What did I do?
Shift + RClick Point 1 -> Shift + RClick Point 2 -> P + LClick Point 3.

Result:
Unit moves to Point 1, Moves to Point 2, Start patroling between Point 2 and Point 3.

![wargus_patrol](https://user-images.githubusercontent.com/17779789/74954378-4f486100-5403-11ea-809e-926bbd3c8f96.png)

**Comment by ipochto** [comment]
Hmmm, intresting. Which your version of stratagus?

Shift + RClick Point 1 -> Shift + RClick Point 2 -> P + LClick Point 3.
Point 0 - is the point where units was when I made this orders queue.
And as a result after reached all waypoints units starts patrolling between point 3 and point 0.

![screen02](https://user-images.githubusercontent.com/5509477/74957187-3f874780-5418-11ea-8e4d-e2ea9dbee85b.png)

**Comment by mxdamien** [comment]
Sorry - forgot to write down the last Shift key in my comment but in my tests I pressed it.
I also tried it with the latest master. I will try to do some more testing tommorow

**Comment by mxdamien** [comment]
So CommandPatrolUnit always uses _unit.tilePos_ as starting positions for patroling, which is wrong if there are previous orders in the orders queue. Probably we should check if there is a previous order in the queue and use its goal position as starting point.

https://github.com/Wargus/stratagus/blob/749818369a57a67e83f658f469941d3b0458b22f/src/action/command.cpp#L399-L420

**Comment by timfel** [comment]
Fixed with PR

**Comment by ipochto** [comment]
@mxdamien, thank you!
