### ISSUE TITLE
Vision given by corpses.

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#270]
There is a vision under fog of war until corpse will not absolutely decay.  It makes sense if vision will disappear after shorter period of time - may be while first stage of decay is showed?

**Comment by timfel** [comment]
I thought what we have now is the same in the original

**Comment by ipochto** [comment]
Just checked - warcraft 2: 
1. Fresh corpse - vision as wide as for a live unit;
2. 1st stage decay - vision is 1 tile wide.
3. 2nd stage decay - vision disappear after 1 second.

Then I came back to check if dead body is still there under the fog of war - it was there. 

Maybe this is not so important for single player game, but for multiplayer the longer vision is not good.

**Comment by timfel** [comment]
Ok, sounds like we should fix it :)
