### ISSUE TITLE
Wrong draw order for shadows of flying units;

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#274]
Shadow of the flying units placed ON their owners instead of under. 
For now this shadows represented as Decorations:

`wargus/scripts/ui.lua`:
``` 
DefineDecorations({Index = "ShadowFly", ShowOpponent = true, ShowWhenMax = true, ShowWhenNull = true, Offset = {0, 0}, Method = {"sprite", {"sprite-shadow"}}})
```
And this decoration drawn after the unit-owner sprite. 

More over now this method not allow to make "up-down-floated" shadows (when shadow slightly move up and down according to the its unit down-up movements). *In the original warcraf 2 air units always slightly floats up and down within current tile (Not implemented in Stratagus yet). 

I see 2 possible ways to fix: 
1. Update show Decorations code to make it possible to draw them under unit.
2. Switch to draw shadows by DrawShadows() (see `src/unit_draw.cpp`). In this case adding of floating feature will be simplier than in previous case.

IMHO second one is more correct.

**Comment by timfel** [comment]
Fixed with the migration to SDL2: https://github.com/Wargus/stratagus/commit/7ec778474d838cf4a207b48f8f6404b86dbce523
