### ISSUE TITLE
Flame on burning buildings is visible under fog of war.

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#278]
If enemy building which seen before, but now being under the fog of war, will start burn - flame will appear on it. Flame will disappear after the building being destroyed/repaired.

Screenshots of a network game:
![image](https://user-images.githubusercontent.com/5509477/80323429-07471f80-8834-11ea-8488-39737efb0cfc.png)
![image](https://user-images.githubusercontent.com/5509477/80323444-1b8b1c80-8834-11ea-82e5-6b08c887bad1.png)
![image](https://user-images.githubusercontent.com/5509477/80323454-2c3b9280-8834-11ea-918a-2ab0723e7485.png)
![image](https://user-images.githubusercontent.com/5509477/80323468-39f11800-8834-11ea-8a9e-66e6a02bf0f9.png)

**Comment by DinkyDyeAussie** [comment]
Should be a simple case of making the flame invisible under fog by changing a value in the lua files.

**Comment by ipochto** [comment]
Upd:
Sorry, I was wrong. A small part of the flame sprite hit the visible area (marked by red), so engine draws it full.
![image](https://user-images.githubusercontent.com/5509477/80381561-c38efd00-88a9-11ea-912f-ab35cd58250e.png) 
![image](https://user-images.githubusercontent.com/5509477/80381627-e15c6200-88a9-11ea-8c0d-49a042c47c93.png)

**Comment by DinkyDyeAussie** [comment]
Because all sprites are read and plotted from the top-left corner...makes sense.
