### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by rafalp** [Wargus/stratagus#288]
I've noticed the repo has "unmaintained" as tag. However it seems that there's still activity on the repo. Does that mean that tag is incorrect?

**Comment by timfel** [comment]
It's probably more a "help wanted". There's some activity, but it's on and off and there's a few months quiet period every year where no one even has time to respond to issues :(

**Comment by timfel** [comment]
Changed to "help-wanted"

**Comment by rafalp** [comment]
Can relate with this.

Still, thank you for your clarification!
