### ISSUE TITLE
SDL2 shader extensions slow on old linux box

### ISSUE THREAD

**Issue by akce** [Wargus/stratagus#291]
I'm using the new SDL2 stratagus on an *old* (about 13 years) linux desktop.

I'm fairly sure it's not hardware accelerated.

Unfortunately for me, SDL2 will allow (what i'm assuming) is a software opengl but it's slow.

I can get stratagus to work at what looks like the original SDL1 speed by commenting out shader extensions:
```diff
diff --git a/src/video/sdl.cpp b/src/video/sdl.cpp
index a2971d8ae..e7afe02d7 100644
--- a/src/video/sdl.cpp
+++ b/src/video/sdl.cpp
@@ -329,7 +329,7 @@ void InitVideoSdl()
 	SDL_GetRendererInfo(TheRenderer, &rendererInfo);
 	if(!strncmp(rendererInfo.name, "opengl", 6)) {
 		puts("[Renderer] Got OpenGL");
-		CanUseShaders = LoadShaderExtensions();
+		//CanUseShaders = LoadShaderExtensions();
 	}
 	SDL_SetRenderDrawColor(TheRenderer, 0, 0, 0, 255);
 	Video.ResizeScreen(Video.Width, Video.Height);
```
I'm wondering if there's a better solution?

If not, maybe add a command line option to disable shader extensions? (I'm happy to code and make a pull request for this or test an implementation.)

Hardware info (edited for brevity):
```
$ cat /proc/cpuinfo
..
model name	: Intel(R) Core(TM)2 CPU          6400  @ 2.13GHz
..
```
```
$ lspci
..
00:02.0 VGA compatible controller: Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03)
..
```

**Comment by ipochto** [comment]
You can disable shaders in game menu. (F10)->Options->Preferences and select "none" in the Shader field.

**Comment by akce** [comment]
Marvelous, this solves my problem exactly! Thanks for showing me the way. :)

**Comment by ipochto** [comment]
@timfel, maybe to add this option to "Video" menu too?
