### ISSUE TITLE
Build error CXX_STANDARD

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#295]
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:640 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:640 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could not find StackTrace
-- Found OggVorbis: /usr/lib64/libogg.so;/usr/lib64/libvorbis.so
==================================
Debug mode: No (Enable by param -DCMAKE_BUILD_TYPE=Debug)
Profiling mode: No (Enable by param -DCMAKE_BUILD_TYPE=Profile)
Strip executables: No (Enable by param -DENABLE_STRIP=ON)
Static linking: No (Enable by param -DENABLE_STATIC=ON)
Place game files in: user directory (Place in game directory with -DENABLE_USEGAMEDIR=ON)
Parallel building in MSVC: Yes (Disable by param -DENABLE_MULTIBUILD=OFF)
Platform: Linux
Redirect stdio: Unsupported on this platform
Touchscreen input: No (Enable by param -DENABLE_TOUCHSCREEN=ON)
Doxygen documentation: No (Enable by param -DENABLE_DOC=ON)
Game development files: No (Enable by param -DENABLE_DEV=ON)
Upx packer: No (Enable by param -DENABLE_UPX=ON)
NSIS Installer: Unsupported on this platform
Bzip2: Found and enabled (Disable by param -DWITH_BZIP2=OFF)
Mng: Found and enabled (Disable by param -DWITH_MNG=OFF)
Ogg/Vorbis: Found and enabled (Disable by param -DWITH_OGGVORBIS=OFF)
StackTrace: Not Found
Theora: Found and enabled (Disable by param -DWITH_THEORA=OFF)
X11: Found and enabled (Disable by param -DWITH_X11=OFF)
==================================
-- Configuring done
CMake Error at CMakeLists.txt:1052 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:1125 (add_executable):
  CMake Error at CMakeLists.txt:1125 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:1099 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:1015 (add_executable):
  CXX_STANDARD is set to invalid value '17'

-- Generating done
-- Build files have been written to: /opt/var/public/Linux/stratagus/build

**Comment by Zombie-Ryushu** [comment]
/opt/var/public/Linux/stratagus/src/include/util.h:52:8: error: ‘uint32_t’ does not name a type
 extern uint32_t FileChecksums;          /// checksums of all loaded lua files
        ^
/opt/var/public/Linux/stratagus/src/include/util.h:85:8: error: ‘uint32_t’ does not name a type
 extern uint32_t fletcher32(const std::string &content);
        ^
In file included from /opt/var/public/Linux/stratagus/src/action/action_attack.cpp:50:0:
/opt/var/public/Linux/stratagus/src/include/player.h:80:1: error: scoped enums only available with -std=c++11 or -std=gnu++11 [-Werror]
 enum class RevealTypes 
 ^
/opt/var/public/Linux/stratagus/src/include/player.h:91:42: error: extended initializer lists only available with -std=c++11 or -std=gnu++11 [-Werror]
  static inline RevealTypes RevelationFor { RevealTypes::cNoRevelation }; /// type of revelation (when player lost 
                                          ^
/opt/var/public/Linux/stratagus/src/include/player.h:91:44: error: ‘RevealTypes’ is not a class or namespace
  static inline RevealTypes RevelationFor { RevealTypes::cNoRevelation }; /// type of revelation (when player lost 
                                            ^
/opt/var/public/Linux/stratagus/src/include/player.h:91:71: error: ‘RevelationFor’ declared as an ‘inline’ field
  static inline RevealTypes RevelationFor { RevealTypes::cNoRevelation }; /// type of revelation (when player lost 
                                                                       ^
/opt/var/public/Linux/stratagus/src/include/player.h:91:71: error: ISO C++ forbids in-class initialization of non-const static member ‘CPlayer::RevelationFor’
In file included from /opt/var/public/Linux/stratagus/src/action/action_attack.cpp:50:0:
/opt/var/public/Linux/stratagus/src/include/player.h:110:45: error: ‘RevealedPlayers’ declared as an ‘inline’ field
  static inline std::vector<const CPlayer *> RevealedPlayers; 
                                             ^
/opt/var/public/Linux/stratagus/src/include/player.h:163:33: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
  int  LostMainFacilityTimer { 0 };/// The timer for when the player lost the last town hall 
                                 ^
/opt/var/public/Linux/stratagus/src/include/player.h:284:26: error: non-static data member initializers only available with -std=c++11 or -std=gnu++11 [-Werror]
  bool isRevealed { false };  /// whether the player has been revealed (i.e. after losing the last Town Hall)
                          ^
/opt/var/public/Linux/stratagus/src/include/player.h:163:29: error: extended initializer lists only available with -std=c++11 or -std=gnu++11 [-Werror]
  int  LostMainFacilityTimer { 0 };/// The timer for when the player lost the last town hall 
                             ^
/opt/var/public/Linux/stratagus/src/include/player.h:163:33: error: extended initializer lists only available with -std=c++11 or -std=gnu++11 [-Werror]
  int  LostMainFacilityTimer { 0 };/// The timer for when the player lost the last town hall 
                                 ^
/opt/var/public/Linux/stratagus/src/include/player.h:284:18: error: extended initializer lists only available with -std=c++11 or -std=gnu++11 [-Werror]
  bool isRevealed { false };  /// whether the player has been revealed (i.e. after losing the last Town Hall)
                  ^
/opt/var/public/Linux/stratagus/src/include/player.h:284:26: error: extended initializer lists only available with -std=c++11 or -std=gnu++11 [-Werror]
  bool isRevealed { false };  /// whether the player has been revealed (i.e. after losing the last Town Hall)
                          ^
/opt/var/public/Linux/stratagus/src/include/player.h: In static member function ‘static const bool CPlayer::IsRevelationEnabled()’:
/opt/var/public/Linux/stratagus/src/include/player.h:98:36: error: ‘RevealTypes’ is not a class or namespace
   return CPlayer::RevelationFor != RevealTypes::cNoRevelation; 
                                    ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/stratagus.dir/build.make:90: CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/stratagus.dir/all] Error 2

**Comment by timfel** [comment]
Your cmake and possibly also your C compiler are too old. They need to support C++17, so you need a distribution and toolset newer than that
