### ISSUE TITLE
error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#296]
63%] Building CXX object CMakeFiles/stratagus.dir/src/particle/radialparticle.cpp.o
/usr/bin/c++   -DHAVE_GETOPT -DHAVE_STRCASESTR -DHAVE_STRNLEN -DPIXMAPS=\"/usr/share/pixmaps\" -DUSE_BZ2LIB -DUSE_FLUIDSYNTH -DUSE_LINUX -DUSE_MIKMOD -DUSE_MNG -DUSE_OPENGL -DUSE_THEORA -DUSE_VORBIS -DUSE_X11 -DUSE_ZLIB -I/builddir/build/BUILD/stratagus-2.4.3/src/include -I/builddir/build/BUILD/stratagus-2.4.3/src/guichan/include -I/builddir/build/BUILD/stratagus-2.4.3/src/guichan/include/guichan -I/builddir/build/BUILD/stratagus-2.4.3/build -I/usr/include/SDL  -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -fsigned-char -std=gnu++0x -Werror   -o CMakeFiles/stratagus.dir/src/particle/radialparticle.cpp.o -c /builddir/build/BUILD/stratagus-2.4.3/src/particle/radialparticle.cpp
/builddir/build/BUILD/stratagus-2.4.3/src/network/master.cpp: In member function 'int CMetaClient::CreateGame(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/master.cpp:215:42: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   ipport += inet_ntoa(((struct in_addr *)ips)[0]);
                                          ^
[ 63%] Building CXX object CMakeFiles/stratagus.dir/src/particle/particlemanager.cpp.o
/usr/bin/c++   -DHAVE_GETOPT -DHAVE_STRCASESTR -DHAVE_STRNLEN -DPIXMAPS=\"/usr/share/pixmaps\" -DUSE_BZ2LIB -DUSE_FLUIDSYNTH -DUSE_LINUX -DUSE_MIKMOD -DUSE_MNG -DUSE_OPENGL -DUSE_THEORA -DUSE_VORBIS -DUSE_X11 -DUSE_ZLIB -I/builddir/build/BUILD/stratagus-2.4.3/src/include -I/builddir/build/BUILD/stratagus-2.4.3/src/guichan/include -I/builddir/build/BUILD/stratagus-2.4.3/src/guichan/include/guichan -I/builddir/build/BUILD/stratagus-2.4.3/build -I/usr/include/SDL  -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -fsigned-char -std=gnu++0x -Werror   -o CMakeFiles/stratagus.dir/src/particle/particlemanager.cpp.o -c /builddir/build/BUILD/stratagus-2.4.3/src/particle/particlemanager.cpp
cc1plus: all warnings being treated as errors
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'Socket NetOpenUDP(long unsigned int, int)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:311:40: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
   if (bind(sockfd, (struct sockaddr *)&sock_addr, sizeof(sock_addr)) < 0) {
                                        ^
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'Socket NetOpenTCP(const char*, int)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:350:40: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
   if (bind(sockfd, (struct sockaddr *)&sock_addr, sizeof(sock_addr)) < 0) {
                                        ^
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'int NetConnectTCP(Socket, long unsigned int, int)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:387:42: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
  if (connect(sockfd, (struct sockaddr *)&sa, sizeof(sa)) < 0) {
                                          ^
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'int NetRecvUDP(Socket, void*, int, long unsigned int*, int*)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:503:83: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
  const int l = recvfrom(sockfd, (recvfrombuftype)buf, len, 0, (struct sockaddr *)&sock_addr, &n);
                                                                                   ^
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'int NetSendUDP(Socket, long unsigned int, int, const void*, int)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:569:72: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
  return sendto(sockfd, (sendtobuftype)buf, len, 0, (struct sockaddr *)&sock_addr, n);
                                                                        ^
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp: In function 'Socket NetAcceptTCP(Socket, long unsigned int*, int*)':
/builddir/build/BUILD/stratagus-2.4.3/src/network/net_lowlevel.cpp:612:53: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
  Socket socket = accept(sockfd, (struct sockaddr *)&sa, &len);
                                                     ^
make[2]: *** [CMakeFiles/stratagus.dir/build.make:3093: CMakeFiles/stratagus.dir/src/network/master.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/stratagus.dir/build.make:3045: CMakeFiles/stratagus.dir/src/network/net_lowlevel.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/stratagus-2.4.3/build'
make[1]: Leaving directory '/builddir/build/BUILD/stratagus-2.4.3/build'
make[1]: *** [CMakeFiles/Makefile2:140: CMakeFiles/stratagus.dir/all] Error 2
make: *** [Makefile:131: all] Error 2

**Comment by timfel** [comment]
Please add some information about your platform, compiler and cmake versions, and commands run to compile.

**Comment by Zombie-Ryushu** [comment]
Mageia Linux.
cmake 3.7.2

+ /usr/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF '-DCMAKE_MODULE_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,--unresolved-symbols=ignore-all' -DENABLE_DEV=ON

**Comment by ipochto** [comment]
Output of these commands too, please:
```
$ uname -a
$ gcc -v
$ clang -v
```

**Comment by Zombie-Ryushu** [comment]
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/lib64 --mandir=/usr/share/man --infodir=/usr/share/info --disable-libjava-multilib --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-java-awt=gtk --enable-gtk-cairo --with-cloog --with-ppl --enable-cloog-backend=isl --disable-cloog-version-check --disable-libssp --disable-libunwind-exceptions --disable-werror --enable-__cxa_atexit --enable-gold=default --with-plugin-ld=/usr/bin/ld --enable-bootstrap --enable-checking=release --enable-gnu-unique-object --enable-languages=c,ada,c++,fortran,go,java,lto,objc,obj-c++ --enable-linker-build-id --enable-plugin --enable-lto --enable-shared --enable-threads=posix --with-system-zlib --with-bugurl=http://bugs.rosalinux.ru/ --with-tune=generic --with-arch_32=i586 --with-multilib-list=m32,m64 --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu
Thread model: posix

**Comment by Zombie-Ryushu** [comment]
$ uname -a
Linux olympia 4.9.155-nrj-desktop
clang 8.0.1

**Comment by Zombie-Ryushu** [comment]
Let me give you a build log from an Automated Build Farm I use to build Packages like this.

**Comment by Zombie-Ryushu** [comment]
And... its down again.

**Comment by ipochto** [comment]
Your gcc version is very old. You need to upgrade it.
Or you can try to switch to clang compiler. 8.0.1 version you have is enough to support C++17 fetures.

**Comment by timfel** [comment]
@Zombie-Ryushu note that we dropped support for anything older than Ubuntu 18.04, that is, at least Linux kernel 4.15 and gcc 7

**Comment by timfel** [comment]
For reference, you can always take a look at our Travis builds (e.g. here: https://travis-ci.org/github/Wargus/stratagus/jobs/703046128). They represent the oldest version we support, if you open the "Build System Information" you will see what versions that uses.

**Comment by Zombie-Ryushu** [comment]
Got it to compile with:
export CXXFLAGS="%{optflags} -Wno-error=strict-aliasing"
