### ISSUE TITLE
cmake cannot fiind openMP.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#297]
-- sdl2 found: includes in /usr/include/SDL2, library in /usr/lib64/libSDL2.so;-lpthread
-- Found SDL2_mixer: /usr/lib64/libSDL2_mixer.so (found version "2.0.4") 
-- Found SDL2_image: /usr/lib64/libSDL2_image.so (found version "2.0.5") 
-- Found program tolua++: /usr/bin/tolua++
-- Found library tolua++: /usr/lib64/libtolua++.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Could not find StackTrace
-- Found MNG: /usr/lib64/libmng.so
-- Looking for vorbis_bitrate_addblock in vorbis
-- Looking for vorbis_bitrate_addblock in vorbis - found
-- Found OggVorbis: /usr/lib64/libogg.so;/usr/lib64/libvorbis.so
-- theora found: includes in /usr/include, library in /usr/lib64/libtheora.so;/usr/lib64/libogg.so;/usr/lib64/libvorbis.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.31.1
-- Found Sqlite: /usr/include  
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of errno_t
-- Check size of errno_t - failed
-- Looking for strcpy_s
-- Looking for strcpy_s - not found
-- Looking for strncpy_s
-- Looking for strncpy_s - not found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for strcat_s
-- Looking for strcat_s - not found
==================================
Debug mode: No (Enable by param -DCMAKE_BUILD_TYPE=Debug)
Profiling mode: No (Enable by param -DCMAKE_BUILD_TYPE=Profile)
Strip executables: No (Enable by param -DENABLE_STRIP=ON)
Static linking: No (Enable by param -DENABLE_STATIC=ON)
Place game files in: user directory (Place in game directory with -DENABLE_USEGAMEDIR=ON)
Parallel building in MSVC: Yes (Disable by param -DENABLE_MULTIBUILD=OFF)
Platform: Linux
Redirect stdio: Unsupported on this platform
Touchscreen input: No (Enable by param -DENABLE_TOUCHSCREEN=ON)
Doxygen documentation: No (Enable by param -DENABLE_DOC=ON)
Game development files: Yes (Disable by param -DENABLE_DEV=OFF)
Upx packer: No (Enable by param -DENABLE_UPX=ON)
NSIS Installer: Unsupported on this platform
Bzip2: Found and enabled (Disable by param -DWITH_BZIP2=OFF)
Mng: Found and enabled (Disable by param -DWITH_MNG=OFF)
Ogg/Vorbis: Found and enabled (Disable by param -DWITH_OGGVORBIS=OFF)
StackTrace: Not Found
Theora: Found and enabled (Disable by param -DWITH_THEORA=OFF)
X11: Found and enabled (Disable by param -DWITH_X11=OFF)
==================================
-- Configuring done
CMake Error at CMakeLists.txt:1053 (add_executable):
  CXX_STANDARD is set to invalid value '17'
CMake Error at CMakeLists.txt:1126 (add_executable):
  CXX_STANDARD is set to invalid value '17'
CMake Error at CMakeLists.txt:1100 (add_executable):
  CXX_STANDARD is set to invalid value '17'
CMake Error at CMakeLists.txt:1016 (add_executable):
  CXX_STANDARD is set to invalid value '17'
-- Generating done
-- Build files have been written to: /builddir/build/BUILD/stratagus-master/build
CMake Warning:
  Manually-specified variables were not used by the project:
    BUILD_STATIC_LIBS
    CMAKE_INSTALL_LIBDIR
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.77550 (%build)
    Bad exit status from /var/tmp/rpm-tmp.77550 (%build)
Child returncode was: 1

**Comment by timfel** [comment]
What's the issue with enabling OpenMP on your platform?

**Comment by timfel** [comment]
OpenMP is optional in CMake now.
