### ISSUE TITLE
Selectable magnification factor

### ISSUE THREAD

**Issue by mgtroyas** [Wargus/stratagus#298]
Hi, additionally to render all UI and scenario at 1x on current resolution, or zooming/stretching everything to original ratio, I suggest allowing the user to to choose the magnification factor for scenario and UI.

I play on a 2560x1080 ultrawide monitor, the first option makes everything too small, the second stretches the UI not preserving the original aspect ratio, and makes everything too big.

You can check Dune Legacy, a source port for the original Dune game, it allow this letting a customizable pixel perfect experience (if using integer magnification factors). It even lets choose a different ratio for menubar, sidebar and scenario.

For instance I'm attaching a creenshot at:
menubar_scale=2.00
sidebar_scale=2.00
viewport_scale=2.00

![OpenDune](https://user-images.githubusercontent.com/30797135/87687565-2cd62c00-c786-11ea-9889-ff3faec3fff4.png)

**Comment by timfel** [comment]
this is what we already have on master, the new scaling will be released with 3.0.0
