### ISSUE TITLE
Wayland support question

### ISSUE THREAD

**Issue by hanetzer** [Wargus/stratagus#302]
Just bought the GoG WC2BNE, found a strange 'issue'. Theoretically, using sdl2 of a recent
version should let you do `SDL_VIDEODRIVER=wayland appname` to run via wayland.
Doing `SDL_VIDEODRIVER=wayland wargus` throws the following error:

```
Stratagus failed to load game data. If you just launched the game without any arguments, this may indicate a bug
with the extraction process. Please report this on https://github.com/Wargus/stratagus/issues/new, and please give
details, including: operating system, installation path, username, kind of source CD. A possible solution is to remove
the hidden folder ~/.stratagus/data.Wargus).
```
Operating system is gentoo linux, DE is sway (i3wm for wayland basically), stratagus/wargus are 2.4.3, GoG WC2BNE.
I think it may have something to do with how wargus launches stratagus.

Given that, is it possible to directly launch strategus into a wargus game for testing purposes?

**Comment by hanetzer** [comment]
Note, using this same `~/.stratagus/data.Wargus` directory using x11 or xwayland launches fine.

**Comment by timfel** [comment]
I've just tested on sway, making sure that xwayland is not running, and it works with `SDL_VIDEODRIVER=wayland`.

You can run stratagus directly by using `stratagus -d ~/.stratagus/data.Wargus`

**Comment by timfel** [comment]
Running on waylands works on master
