### ISSUE TITLE
make fails with undefined reference to symbol 'lua_setglobal'

### ISSUE THREAD

**Issue by erik55** [Wargus/stratagus#310]
### Step 1: `cmake`

    $ cmake ..
    -- The C compiler identification is GNU 9.3.1
    -- The CXX compiler identification is GNU 9.3.1
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc - works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ - works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Lua51: /usr/lib64/liblua-5.1.so;/usr/lib64/libm.so (found version "") 
    -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
    -- Found PNG: /usr/lib64/libpng.so (found version "1.6.37") 
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- sdl2 found: includes in /usr/include/SDL2, library in /usr/lib64/libSDL2.so;-lpthread
    -- Found SDL2_mixer: /usr/lib64/libSDL2_mixer.so (found version "2.0.4") 
    -- Found SDL2_image: /usr/lib64/libSDL2_image.so (found version "2.0.5") 
    -- Found program tolua++: /usr/bin/tolua++
    -- Found library tolua++: /usr/lib64/libtolua++.so
    -- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.8") 
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Could not find StackTrace
    -- Could not find MNG
    -- Could NOT find OggVorbis libraries
    -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of errno_t
    -- Check size of errno_t - failed
    -- Looking for strcpy_s
    -- Looking for strcpy_s - not found
    -- Looking for strncpy_s
    -- Looking for strncpy_s - not found
    -- Looking for strcasestr
    -- Looking for strcasestr - found
    -- Looking for strnlen
    -- Looking for strnlen - found
    -- Looking for getopt
    -- Looking for getopt - found
    -- Looking for strcat_s
    -- Looking for strcat_s - not found
    ==================================
    Debug mode: No (Enable by param -DCMAKE_BUILD_TYPE=Debug)
    Profiling mode: No (Enable by param -DCMAKE_BUILD_TYPE=Profile)
    Strip executables: No (Enable by param -DENABLE_STRIP=ON)
    Static linking: No (Enable by param -DENABLE_STATIC=ON)
    Place game files in: user directory (Place in game directory with -DENABLE_USEGAMEDIR=ON)
    Parallel building in MSVC: Yes (Disable by param -DENABLE_MULTIBUILD=OFF)
    Platform: Linux
    Redirect stdio: Unsupported on this platform
    Touchscreen input: No (Enable by param -DENABLE_TOUCHSCREEN=ON)
    Doxygen documentation: No (Enable by param -DENABLE_DOC=ON)
    Game development files: No (Enable by param -DENABLE_DEV=ON)
    Upx packer: No (Enable by param -DENABLE_UPX=ON)
    NSIS Installer: Unsupported on this platform
    Bzip2: Found and enabled (Disable by param -DWITH_BZIP2=OFF)
    Mng: Not Found
    Ogg/Vorbis: Not Found
    StackTrace: Not Found
    Theora: Not Found
    ==================================
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/erik/Downloads/firefox/stratagus-3.0.0/stratagus-3.0.0/build

### Step 2: `make`

    $ make -j 4
    Scanning dependencies of target genversion
    Scanning dependencies of target png2stratagus
    [  1%] Building CXX object CMakeFiles/genversion.dir/tools/genversion.cpp.o
    [  1%] Building CXX object CMakeFiles/png2stratagus.dir/tools/png2stratagus.cpp.o
    [  1%] Linking CXX executable genversion
    [  1%] Built target genversion
    Cannot get git revision
    -1 -1 -1 -1 - 3 0 0 0
    ver update
    [genversion] update needed
    Scanning dependencies of target version-generated.h
    [  2%] Generating tolua.cpp
    Cannot get git revision
    [genversion] update needed
    [  2%] Built target version-generated.h
    [  2%] Linking CXX executable png2stratagus

    ** tolua warning: Mapping variable to global may degrade performance.

    Scanning dependencies of target stratagus
    [  2%] Built target png2stratagus
    [  3%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o
    [  3%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_build.cpp.o
    [  3%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_board.cpp.o
    [  4%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_built.cpp.o
    [  4%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_defend.cpp.o

    …

    [ 98%] Building CXX object CMakeFiles/stratagus.dir/src/video/video.cpp.o
    [ 99%] Building CXX object CMakeFiles/stratagus.dir/src/video/shaders.cpp.o
    [ 99%] Building CXX object CMakeFiles/stratagus.dir/tolua.cpp.o
    [100%] Linking CXX executable stratagus
    /usr/bin/ld: CMakeFiles/stratagus.dir/src/animation/animation.cpp.o: undefined reference to symbol 'lua_setglobal'
    /usr/bin/ld: /usr/lib64/liblua-5.3.so: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    make[2]: *** [CMakeFiles/stratagus.dir/build.make:3288: stratagus] Error 1
    make[1]: *** [CMakeFiles/Makefile2:130: CMakeFiles/stratagus.dir/all] Error 2
    make: *** [Makefile:150: all] Error 2

What can I do now?

I am on Fedora 31. And I am using

    Name        : lua
    Version     : 5.3.5
    Release     : 8.fc31

and 

    Name        : tolua++
    Version     : 1.0.93
    Release     : 27.fc31

if that is relevant.

**Comment by timfel** [comment]
You need to use Lua 5.1. We try to support 5.2 and 5.3, but that is not tested.

**Comment by timfel** [comment]
We're happy to accept PRs to restore Lua 5.3 compatibility. But 5.1 needs to continue to work, since we measured 5.3 to be considerably slower than 5.1

**Comment by timfel** [comment]
Closing, since we won't fix this (but will accept PRs)
