### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/stratagus#311]
Theora: Found and enabled (Disable by param -DWITH_THEORA=OFF)
==================================
-- Configuring done
CMake Error at CMakeLists.txt:1093 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:1062 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:1025 (add_executable):
  CXX_STANDARD is set to invalid value '17'

-- Generating done

**Comment by timfel** [comment]
You're distribution (and thus your cmake and c++ compiler) are too old. We dropped support for anything older than Ubuntu 18.04.5
