### ISSUE TITLE
Build fails with -Werror=odr (lto link)

### ISSUE THREAD

**Issue by mnhauke** [Wargus/stratagus#312]
Build fails on openSUSE Tumbleweed with gcc10 and LTO enabled:

```
[  264s] /home/abuild/rpmbuild/BUILD/stratagus-3.0.0/src/network/online_service.cpp:694:7: error: type 'struct NetworkState' violates the C++ One Definition Rule [-Werror=odr]
[  264s]   694 | class NetworkState {
[  264s]       |       ^
[  264s] /home/abuild/rpmbuild/BUILD/stratagus-3.0.0/src/network/netconnect.cpp:66:8: note: a type with different virtual table pointers is defined in another translation unit
[  264s]    66 | struct NetworkState {
[  264s]       |        ^
[  266s] lto1: all warnings being treated as errors
[  266s] lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
[  266s] compilation terminated.
[  266s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: error: lto-wrapper failed
[  267s] collect2: error: ld returned 1 exit status
```

**Comment by timfel** [comment]
Thanks! Do you want to open PRs also for #313? I will probably not get to it in the next week.

**Comment by mnhauke** [comment]
> Thanks! Do you want to open PRs also for #313? I will probably not get to it in the next week.

I fear that I cannot really help here with proper fixes with my rusty c++ skills. I have added workarounds for the openSUSE packages by disabling the offending compiler warnings.

**Comment by timfel** [comment]
No worries. I will to fix and add these flags to our CI so we don't run into that in the future. Thank you for the report!
