### ISSUE TITLE
ShowMapLocation incorrect argument

### ISSUE THREAD

**Issue by SimoneStarace** [Wargus/stratagus#318]
I was making my custom map in Wargus and I have found one function called [**ShowMapLocation**](https://htmlpreview.github.io/?https://raw.githubusercontent.com/Wargus/stratagus/master/doc/scripts/game.html#ShowMapLocation) in the Stratagus scripting documentation; more specifically I have copied the example of the documentation:

```
-- Show an area of 6 tiles around location (10,10) for 500 cycles using 'unit-revealer.
    ShowMapLocation(10, 10, 6, 500, "unit-revealer")
```

The only thing I have changed was only the first two integers, which are the _X_ and _Y_ position. The function isn't putted in a trigger instead it's in a _sms_ file where are defined the players setup and units but every time I try to play the map, only to check if this function works, I always get the following error:

```
/build/stratagus-A5HbDh/stratagus-3.0.0/src/map/script_map.cpp:187: CclShowMapLocation: incorrect argument
incorrect argument
stack traceback:
	[C]: in function 'ShowMapLocation'
	[string "/home/user/.stratagus/data.Wargus/maps/Th..."]:377: in main chunk
	[C]: in function 'StartMap'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:854: in function 'RunMap'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1306: in function 'callback'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:341: in function <[string "/home/simone/.stratagus/data.Wargus/scripts..."]:339>
	[C]: in function 'run'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1558: in function 'RunSinglePlayerGameMenu'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:36: in main chunk
	[C]: in function 'Load'
	...
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1063: in function 'callback'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:341: in function <[string "/home/simone/.stratagus/data.Wargus/scripts..."]:339>
	[C]: in function 'run'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1070: in function 'RunSinglePlayerTypeMenu'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1580: in function 'callback'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:341: in function <[string "/home/simone/.stratagus/data.Wargus/scripts..."]:339>
	[C]: in function 'run'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1609: in function 'BuildProgramStartMenu'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1621: in function 'RunProgramStartMenu'
	[string "/home/user/.stratagus/data.Wargus/scripts..."]:1779: in main chunk
```

I have also checked the source code for the function call CclShowMapLocation and it seems it's written correctly on how it should handle the Lua parameters.

https://github.com/Wargus/stratagus/blob/3a7ba1775870faa25d94cdf93397c1d47e2c9492/src/map/script_map.cpp#L177-L206

I really don't know how to deal with this problem.

**Comment by timfel** [comment]
The first line of the function is wrong. It should be `LuaCheckArgs(l, 5)`, because there's 5 arguments, not 4.

**Comment by SimoneStarace** [comment]
> The first line of the function is wrong. It should be `LuaCheckArgs(l, 5)`, because there's 5 arguments, not 4.

Ok I can change the value and make a pull request so this can be fixed.
