### ISSUE TITLE
actions.cpp: Wrong conditions for UnHideUnit() call.

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#335]
*From discord, left it here just so it wouldn't get lost.

There is a piece of code here:
https://github.com/Wargus/stratagus/blob/80cfecbd83f26fdaccf52531c9fc6aa236d70dd3/src/action/actions.cpp#L310

```C++
        const bool lastStatusIsHidden = unit.Variable[INVISIBLE_INDEX].Value > 0;
	if (lastStatusIsHidden && unit.Variable[INVISIBLE_INDEX].Value == 0) {
		UnHideUnit(unit);
	}
```
@Andrettin:
>"lastStatusIsHidden" and "unit.Variable[INVISIBLE_INDEX].Value == 0" can never be true at the same time so "UnHideUnit" will never be triggered.
>maybe the "lastStatusIsHidden" initialization should be placed before the buff variable decrement?

>so it is a piece of code which is never triggered, and even if it were would have no effect as in effect what we have is this:
```C++
   if (unit.Variable[INVISIBLE_INDEX].Value > 0 && unit.Variable[INVISIBLE_INDEX].Value == 0) {
        unit.Variable[INVISIBLE_INDEX].Value = 0;
    }
```

**Comment by timfel** [comment]
I deleted the code. I think it used to be more interesting, because `UnHideUnit(unit)` used to be
```c++
void UnHideUnit(CUnit *unit)
{
	const int action = unit->CurrentAction();
	const bool mark_guard = (action == UnitActionStill || 
						action == UnitActionStandGround) && 
						unit->Variable[INVISIBLE_INDEX].Value > 0;
	unit->Variable[INVISIBLE_INDEX].Value = 0;
	if (mark_guard)
	{
		MapMarkUnitGuard(unit);
	}					
}
```

But since all this changed way before my time, I guess this was just forgotten and has been uselessly doing nothing ever since.
