### ISSUE TITLE
build fails - lua_objlen

### ISSUE THREAD

**Issue by andmarti1424** [Wargus/stratagus#343]
Hello. I am getting this
` Building CXX object CMakeFiles/stratagus.dir/src/network/netconnect.cpp.o
/home/mongo/src/stratagus.wargus/stratagus/src/network/netconnect.cpp: In lambda function:
/home/mongo/src/stratagus.wargus/stratagus/src/network/netconnect.cpp:1882:26: error: ‘lua_objlen’ was not declared in this scope; did you mean ‘lua_rawlen’?
 1882 |                 auto i = lua_objlen(l, -1) + 1;
      |                          ^~~~~~~~~~
      |                          lua_rawlen
make[2]: *** [CMakeFiles/stratagus.dir/build.make:1880: CMakeFiles/stratagus.dir/src/network/netconnect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/stratagus.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

Is this a lua issue?
I have both lua 5.1 and lua5.2..
Thanks.

**Comment by timfel** [comment]
It looks like your build is running against Lua 5.2, where this function no longer exists. Can you make sure you are using 5.1?

**Comment by andmarti1424** [comment]
I see. Its there a way to force it use v 5.1?

**Comment by timfel** [comment]
I think you can set LUA_INCLUDE_DIR and LUA_LIBRARIES, but I don't actually know

**Comment by andmarti1424** [comment]
This worked for me: `cmake -DLUA_INCLUDE_DIR=/usr/include/lua5.1`

**Comment by andmarti1424** [comment]
thank you

**Comment by timfel** [comment]
you're welcome :)
