### ISSUE TITLE
3.1.0 fails to build with gcc11 - [-Werror=range-loop-construct]

### ISSUE THREAD

**Issue by mnhauke** [Wargus/stratagus#350]
```
online_service.cpp:830:25: error: loop variable 'key' creates a copy from type 'const std::__cxx11::basic_string<char>' [-Werror=range-loop-construct]
[   99s]   830 |         for (const auto key : defaultUserKeys) {
```

**Comment by timfel** [comment]
what distribution is this on (so I can test). Ubuntu 21.10 still currently comes with gcc-11

**Comment by timfel** [comment]
Ah, sorry, I misread your version title. Odd though, I can build just fine with gcc-11 on ubuntu 21.10

**Comment by timfel** [comment]
did you manually enable this warning? I will fix this one, but in general this codebase is so old, there are many many warnings similar to this so I would just not recommend enabling any compiler features or warnings that are not in the cmake script ;)

**Comment by mnhauke** [comment]
Thanks for the fix.

Indeed, I added the (open)SUSE distribution specific CXXFLAGS that should be applied on all builds for official packages ...
``` -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables```

... on the other side I already disabled other compiler warnings build the builds:
```-Wno-class-memaccess -Wno-sizeof-pointer-memaccess -Wno-stringop-truncation```

The issues were on openSUSE Tumbleweed (rolling release model) with
"gcc-Version 11.1.1 20210625 [revision 62bbb113ae68a7e724255e17143520735bcb9ec9] (SUSE Linux)"

**Comment by timfel** [comment]
Yeah, there's been an issue open for a long time that we should fix all warnings, but there's only so much time ;)
