### ISSUE TITLE
AiResearch repeated when multiple buildings of the same type are on the map

### ISSUE THREAD

**Issue by SimoneStarace** [Wargus/stratagus#352]
I was testing one of my Wargus maps when I suddenly encountered a weird behavior from the A.I when units get upgraded. This strange behavior happens when there are multiple buildings where it is possible to research upgrades. For example Elven archers gets upgrades from the Elven Lumber Mill. When there are multiple Elven Lumber Mill it seems the A.I asks to each Lumber Mill to make the research of the upgrade.
So if there are three elven lumber mill the upgrade of the arrows will be researched three times and all the research will be applied to the units, making the units too powerful.

Here is an example on how to reproduce the bug:
![Upgrade Bug](https://user-images.githubusercontent.com/52276600/124471701-7a83e400-dd9d-11eb-9f74-4f20797391e2.gif)

**Comment by timfel** [comment]
I've been reviewing the C++ code, and that shouldn't happen, at least not for the same lua upgrade request. But if you send an upgrade request from lua multiple times, then this can happen. Could that be the case?

**Comment by SimoneStarace** [comment]
> But if you send an upgrade request from lua multiple times, then this can happen. Could that be the case?

I have written this simple A.I inside a custom map which requests the upgrade only once. The problem happens when multiple **active** buildings starts researching the upgrade.
```
local blue_loop = {
    function() return AiSleep(50000) end,
    function() stratagus.gameData.AIState.loop_index[1 + AiPlayer()] = 0; return false; end,
}

local blue_start = {
    function() return AiSleep(AiGetSleepCycles()) end,
    function() return AiSleep(500) end,
    function() return AiResearch(AiUpgradeMissile1()) end,
    function() return AiResearch(AiUpgradeWeapon1()) end,
    function() return AiSleep(1800) end,
    -- function() return AiWait(AiUpgradeMissile1()) end, -- Crashes
    function() return AiResearch(AiUpgradeArmor1()) end,
    function() return AiLoop(blue_loop, stratagus.gameData.AIState.loop_index) end,
}

function blue_ai() return AiLoop(blue_start, stratagus.gameData.AIState.index) end
DefineAi("blue","*","blue",blue_ai)
```

I have written **active** in bold because a solution could be to make a building inactive through the function `SetUnitVariable` so this avoids the problem of the multiple of the same type of building researching the upgrade, but it's a bit annoying setting all, except one, building to inactive.

This picture show the result of setting one building to inactive
![test2](https://user-images.githubusercontent.com/52276600/146458667-3be50565-28af-40a6-a300-771420455287.gif)
