### ISSUE TITLE
Consider closing files more aggressively at least on macOS.

### ISSUE THREAD

**Issue by abenedic** [Wargus/stratagus#373]
Currently on macOS it can run, but there are lots of errors relating to having too many open files.  I can try looking into this more later myself.

**Comment by abenedic** [comment]
One idea I have currently, that I haven't looked much into is maybe pushing most of the static data files from the game extraction processes(wartool, war1tool, etc.) into an sqlite database as in (https://www.sqlite.org/fasterthanfs.html). Since we wouldn't expect them to change much, and for fast lookup we could just index on file name or use an unordered_map or something.

**Comment by timfel** [comment]
That seems like overkill to me. If we go that route, we might as well just do what Warcraft and Starcraft did anyway, and put everything into one file.

**Comment by abenedic** [comment]
Sure, I can look into where we are keeping files open and see if I can reduce the number.
