### ISSUE TITLE
Replace incorrect Russian language with English

### ISSUE THREAD

**Issue by VadimYG** [Wargus/stratagus#381]
Greetings.
Have the following problem:
After installing Vargus and Stratagus, the first time I ran the .exe file, it asked me to add some files from the original W2 folder, which I did. However, I did not pay attention that it was a Russian release of W2. And now in some short menu items, plus the briefing in single missions, the text is displayed incorrectly. I decided that the correct option would be to uninstall Wargus, then install it and provide the folder with the English version on the next request for files.
However, after uninstalling (even with Revo) and reinstalling, the game does not ask for a folder with files, but starts immediately (again with crooked fonts).
Could you suggest the easiest way to solve this problem.
Thanks in advance.
[http://ipic.su/img/img7/fs/2022-01-13_22-15-08.1642101366.png](url)
[http://ipic.su/img/img7/fs/2022-01-13_22-15-15.1642101394.png](url)

**Comment by timfel** [comment]
You have likely installed the system-wide version. You need to delete the `Stratagus` folder in your `My Documents`

**Comment by timfel** [comment]
Russian language text should actually work, but we don't have any russian speaking developers to test as we make changes, so it sometimes breaks for a few years until someone with russian language knowledge can help fix it again

**Comment by timfel** [comment]
Fixed on master.
