### ISSUE TITLE
Compiling in VSCODE on windows 11 not working.

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#389]
I followed the video on stratagus.com pretty much to the letter, right up until the games start compiling.

The video uses VisualStudioTools 2016 version, whereas I using 2022 version tools, but I am selecting the same compiling tools as the video does, which is second from the top out of all the "Visual Studio tools"

It keeps giving me an error.

This is the terminal output when I try to build the project.

[main] Building folder: stratagus 
[main] Configuring folder: stratagus 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DWIN32_CMAKE_PREFIX_PATH:STRING=c:/Games/stratagus\..\dependencies -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Games/stratagus -Bc:/Games/stratagus/build -G "Visual Studio 16 2019" -T v141_xp -A win32
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at CMakeLists.txt:49 (project):
[cmake]   Generator
[cmake] 
[cmake]     Visual Studio 16 2019
[cmake] 
[cmake]   could not find any instance of Visual Studio.
[cmake] 
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Games/stratagus/build/CMakeFiles/CMakeOutput.log".
[kit] Patch Windows SDK bin path from C:\Program Files (x86)\Windows Kits\10\bin\x64 to C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64 for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat

I have both Visual Studio 2022 community edition AND VSCode 2022 installed.

**Comment by timfel** [comment]
As the error says, it tries to use Visual Studio 2019. Open your `settings.json` and change `cmake.generator` and `cmake.toolset`. It may be enough to just remove them, I don't know.

**Comment by DinkyDyeAussie** [comment]
Yeah that didn't work...

**Comment by timfel** [comment]
If you don't install VS 2019, it's not expected to work. VS 2022 dropped support for XP, and the build scripts all enforce XP support. That being said, I will drop XP support in the summer release. I will still stick with VS 2019 though. If you use anything else, you have to set up the settings.json and launch.json manually *before* running *anything* in VSCode, since otherwise the cmake caches and some vscode search path caches will bite you.
