### ISSUE TITLE
Move `~/.stratagus` elsewhere?

### ISSUE THREAD

**Issue by Barbaross93** [Wargus/stratagus#399]
Is it possible to define a custom location for `~/.stratagus`? Personally, I prefer to keep my home directory as clean as possible. It looks like there's a `-d` flag that should do what I want, but all I see are messages related to not finding the game files. Am I missing something? Is there an environment variable I can set?

**Comment by timfel** [comment]
It's not possible to define a custom location for `~/.stratagus`

**Comment by timfel** [comment]
it probably should go into `~/.config/stratagus`, i guess

**Comment by timfel** [comment]
thanks, the last time I checked how XDG specifies that was years ago and I had forgotten. It's only one place in the codebase, iirc, maybe I'll get to it sometime, or someone else will

**Comment by timfel** [comment]
Fixed in master. Data is now extracted to XDG_DATA_HOME and savegames and config files are stored in XDG_CONFIG_HOME
