### ISSUE TITLE
Menu backgrounds not working on Mac OS

### ISSUE THREAD

**Issue by RulerOf** [Wargus/stratagus#404]
Hi. I did a checkout of the v3.2.0 tag for both war1gus and stratagus and built/installed them. M1 chip building native arm64 binaries. Pulled the assets from the DOS version.

Menu backgrounds don't work, and navigating into menus causes upper-level menu text to be "burnt" into the background, making everything illegible:
<img width="1921" alt="image" src="https://user-images.githubusercontent.com/539074/178413584-a5f6932e-15a5-43c2-ba38-4782400e6b83.png">

I got the stack trace when I entered the preferences menu.

The gameplay seems to work well except for a few bugs. Wargus has the same problem, so I'm guessing it's a stratagus issue.

**Comment by RulerOf** [comment]
Wargus example: 
![image](https://user-images.githubusercontent.com/539074/178586920-0741cc5a-643d-4817-bfcd-bd5f22d5920d.png)

**Comment by shinra-electric** [comment]
I think this is probably outdated. The menus are fine on my M1. 

<img width="752" alt="Screenshot 2023-03-14 at 13 46 37" src="https://user-images.githubusercontent.com/50119606/225005431-1311c665-f218-46a6-9c08-12a165d2ad06.png">

I'm using the GOG version though, the DOS version might still have this issue.

**Comment by SimoneStarace** [comment]
Hello @RulerOf there isn't much support for Mac OS but have you retried with the latest version of the engine?

**Comment by Jarod42** [comment]
Closing as probably outdated, reopen it or open another one if problem is still present.
