### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Erikcleric** [Wargus/stratagus#420]
Hi.

I just installed Wargus and pointed it towards my install.mpq, im using Warcraft 2 Battlenet edition from Gog. I have to use that one since i displaced my old CD's at the moment.

It finished extracting but when trying to launch it says "Stratagus failed to load game data."
Safe Graphics Mode executable is the only one that works and it runs just fine.

Im using Windows 10.

Got the game in D:/Games/Wargus with Warcraft 2 in a separate folder.

I wanted to include the crash.dmp file but had to save it as a txt to include it here, not sure where to post dmp files on Github.

Just wondering whats causing this.

/ Erik

[Wargus-extraction.log](https://github.com/Wargus/stratagus/files/9845284/Wargus-extraction.log)
in its separate folder.
[crash txt.txt](https://github.com/Wargus/stratagus/files/9845287/crash.txt.txt)
[stdout.txt](https://github.com/Wargus/stratagus/files/9845290/stdout.txt)

**Comment by SpiReCZ** [comment]
This happens to me too Wargus 3.3.2

**Comment by timfel** [comment]
The only real difference between safe graphics mode and normal mode is software rendering. If it works for you in safe mode, then it's problem with the graphics drivers on your system. I'm sorry, I cannot help you there, but if your system was made in the last 20 years, software rendering is fast enough.
