### ISSUE TITLE
Wargus Multiplayer crashing in 3.3.2

### ISSUE THREAD

**Issue by SpiReCZ** [Wargus/stratagus#422]
Latest version working: 3.2.0
Versions crashing: 3.3.2, 3.3.1, 3.3.0

This is from 3.3.2 portable and using GOG setup_warcraft_ii_2.02_v4_(28734).exe (however WAR2BNECD did the same).

---

Scenario 1 Steps:
1. Go to multiplayer
2. Choose Garden of War (BNE) or any other map
3. Add 1 or more AIs and
4. **Run the game with Dedicated AI Server**
5. **The hosting game crashes**

[stderr.txt](https://github.com/Wargus/stratagus/files/10299771/stderr.txt)
[stdout.txt](https://github.com/Wargus/stratagus/files/10299772/stdout.txt)
[Wargus-extraction.log](https://github.com/Wargus/stratagus/files/10299773/Wargus-extraction.log)
[crash.zip](https://github.com/Wargus/stratagus/files/10299775/crash.zip)

---

Scenario 2 steps:
1. Go to multiplayer
2. Choose Garden of War (BNE) or any other map
3. Add 1 or more AIs and
4. **Let some friend join you**
6. Run the game
7. **Friends game crashes**
8. When i exit the game, the game crashes

Friend:
[stderr.txt](https://github.com/Wargus/stratagus/files/10299810/stderr.txt)
[stdout.txt](https://github.com/Wargus/stratagus/files/10299811/stdout.txt)
[Wargus-extraction.log](https://github.com/Wargus/stratagus/files/10299812/Wargus-extraction.log)
[crash.zip](https://github.com/Wargus/stratagus/files/10299813/crash.zip)

Me:
[stderr.txt](https://github.com/Wargus/stratagus/files/10299982/stderr.txt)
[stdout.txt](https://github.com/Wargus/stratagus/files/10299983/stdout.txt)
[Wargus-extraction.log](https://github.com/Wargus/stratagus/files/10299985/Wargus-extraction.log)
[crash.zip](https://github.com/Wargus/stratagus/files/10299986/crash.zip)

**Comment by timfel** [comment]
Thank you for the detailed report.

- [ ] Scenario 1

    I fixed this issue - another fix in 3.3 for multiplayer setup broke the dedicated AI multiplayer button.

- [ ] Scenario 2 server

    The logs indicate that you tried to start 3 games, you were running Stratagus 3.3.2 and your friend was running 3.2.0. This cannot work. The crash when you exit the game is unrelated to the multiplayer, it is a bug with our sound engine that I hopefully fixed now.

- [ ] Scenario 2 client

    I'm not sure I understand the issue here, it may be due to incompatible versions, but I'm not certain.

**Comment by timfel** [comment]
I think I found out what the issue was in the client crash, but not sure why it happened. I added more debugging output so when it happens again in a newer version I have some more information.
