### ISSUE TITLE
'Open' on lines 70,71,72 in astar.cpp prevents compiling

### ISSUE THREAD

**Issue by evild4ve** [Wargus/stratagus#424]
I doubt this is useful, but to compile 3.3.3 from Master I needed to change one of the files:-

stratagus-master/src/pathfinder/astar.cpp

69 struct Open {
70	uint32_t Open::GetCosts() const;
71	void Open::SetCosts(uint64_t costs);
72	uint32_t Open::GetOffset() const;

It was producing this error:-

```

[  6%] Building CXX object CMakeFiles/stratagus.dir/src/pathfinder/astar.cpp.o
/home/dave/Desktop/stratagus2/stratagus-master/src/pathfinder/astar.cpp:70:9: error: invalid preprocessing directive #uint32_t
   70 | #       uint32_t Open::GetCosts() const;
      |         ^~~~~~~~
/home/dave/Desktop/stratagus2/stratagus-master/src/pathfinder/astar.cpp:71:9: error: invalid preprocessing directive #void
   71 | #       void Open::SetCosts(uint64_t costs);
      |         ^~~~
/home/dave/Desktop/stratagus2/stratagus-master/src/pathfinder/astar.cpp:72:9: error: invalid preprocessing directive #uint32_t
   72 | #       uint32_t Open::GetOffset() const;
      |         ^~~~~~~~
```

I thought perhaps it rejected "Open" being in lines 70,71,72 as well as in line 69. So I changed it to:-

69 struct Open {
70	uint32_t GetCosts() const;
71	void SetCosts(uint64_t costs);
72	uint32_t GetOffset() const;

This worked for me in terms of completing the build, but I fear in case the reduplicated "open" is actually productive and the compiler was rejecting it falsely. I suppose this might be something to do with the AI deciding if it has resources for a building - very much beyond my ken

**Comment by timfel** [comment]
no, you're right, that's an actual bug

**Comment by timfel** [comment]
fixed
