### ISSUE TITLE
adding ultrawide resolutions

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/stratagus#425]
Where in the source code does it create the folders for the supported resolutions in-game? - i.e 2560x1440, 1920x1080 etc...

Would it be hard to add more resolutions? If this has been done then disregard, but I just wanted to ask...

**Comment by timfel** [comment]
You can use any resolution you want as commandline argument or in your preferences.lua.

**Comment by timfel** [comment]
Here it is in 3200x600, for example: 
![image](https://user-images.githubusercontent.com/46235/211208956-a29a0580-4fb7-4d49-abcd-7f7371556491.png)
