### ISSUE TITLE
[macOS] The Cmake HAS_17_FS test fails with Xcode 14.3

### ISSUE THREAD

**Issue by shinra-electric** [Wargus/stratagus#437]
The Cmake HAS_17_FS test fails with Xcode 14.3.
So do the subsequent HAS_EXP_17_FS_WITH_STDC and HAS_EXP_17_FS_WITH_CLIB tests. 

Works fine with Xcode 14.2, so something in Xcode has changed.

**Comment by shinra-electric** [comment]
Just to add to this: Stratagus will build and run fine if I just comment out the checks. Tasted with Wargus, where I also had to comment out the checks.

**Comment by shinra-electric** [comment]
Quick update to this, it doesn't pass using Xcode 15 either.

**Comment by Jarod42** [comment]
I don't have XCode for testing, but indeed the test seems wrong.
Just created #512 for that (but cannot actually test it).
