### ISSUE TITLE
Warcraft 3 

### ISSUE THREAD

**Issue by ShadowWarfare** [Wargus/stratagus#593]
With Stratagus partially supporting Starcraft 1 would it be possible for the devs to consider supporting Warcraft 3 and its expansion the Frozen Throne, if doable?

**Comment by timfel** [comment]
Stratagus is strictly a 2D engine. The only way of "supporting Warcraft 3" would be to write a tool that extracts the Warcraft 3 data and converts all of it into 2d images, and so you basically get a de-make of Warcraft 3.

tl;dr - no
