### ISSUE TITLE
edge scroll (down+right only) broken

### ISSUE THREAD

**Issue by MamiyaOtaru** [Wargus/stratagus#682]
Compiled from git today.

Scrolling with the mouse on the edge of the screen (or window, in windowed mode) works in all directions but down+right.  If the cursor graphic changes to the down+right arrow, no scrolling happens.

Linux.  Same behavior in Wayland or Xorg

**Comment by MamiyaOtaru** [comment]
I'd blame line 201 in interface.h:
constexpr unsigned int ScrollRightDown = ScrollRight | ScrollLeft; /// scroll right + down

from https://github.com/Wargus/stratagus/commit/cc11b81ce287f36ea938dce58e2b5989d286a5a3
only been broken for 8 months haha.  No one noticed?

**Comment by MamiyaOtaru** [comment]
TY!  It's great that you are maintaining this project and refreshing the code.  I just have to wonder how often you actually play the game.  Cause now it scrolls down and left instead of doing nothing at all, but it's still not down and right.  Like fire the game up and try it out the fix or something :D

And I gave you the working line in my comment..  should have done a pull request I guess.

Not mad, just bemused

**Comment by Jarod42** [comment]
I launch the game, but doesn't play full game most of the time.
But indeed, for this "trivial" fix, I have just compile it :-/
Sorry again for the trouble.
